/**
 * Care 24 Japan — legal document contents.
 *
 * GENERATED from the client-provided .docx files (29 July 2026, legal-checked),
 * preserving document order, list structure and tables, with heading structure
 * normalized across both languages. Each document carries separate Japanese and
 * English block lists — the two languages are full texts, not line-by-line
 * translations of each other. Do not hand-edit wording here without a new
 * legal-checked source document.
 *
 * Deviations from source (2026-08-12 docx-fidelity audit):
 * (a) terms.heading.en keeps the half-width "Terms & Conditions" rather than
 *     the docx's full-width "Terms ＆Conditions" (no following space) — a
 *     typographic normalisation, not a wording change.
 * (b) Every other patch in this change set is docx-cited against
 *     output/docx-extract.json block indices:
 *     - privacy_policy blocks 100, 125
 *     - specified_commercial_transactions_disclosure blocks 1, 18, 3, 38, 39, 9, 10
 *     - care_supporter_remuneration_regulations blocks 26, 27, 28, 1, 34
 *     - cancellation_policy blocks 1, 22
 *     See <run>/output/patch-legal.py for the exact substitutions applied.
 * (c) 2026-08-12 SEO/AEO hygiene fix (F-15): tokushoho's literal
 *     "［料金表等へのリンク］" placeholders now link to the live /pricing and
 *     /cancellation-policy routes (both pages already existed), and the
 *     stale "page to be created later" notes were removed since those pages
 *     are live. Paragraph text supports inline `[label](/path)` markdown-style
 *     links, rendered by LegalDocPage.tsx. The "［〇］月［〇］日 制定"
 *     enactment-date placeholders in `terms` were left untouched per policy —
 *     see the TODO comments directly above those blocks.
 */

import type { Bilingual } from "./copy";

export type LegalBlock =
  | { type: "h2" | "h3" | "p"; text: string }
  | { type: "li"; list: "ul" | "ol"; text: string }
  | { type: "table"; rows: string[][] };

export type LegalDoc = {
  heading: Bilingual;
  body: { ja: LegalBlock[]; en: LegalBlock[] };
};

export const legalDocs = {
  privacy: {
    heading: { ja: "プライバシーポリシー", en: "Privacy Policy" },
    body: {
      ja: [
        { type: "p", text: "メディカルインフォマティクス株式会社（以下「当社」といいます。）は、ステークホルダーの皆様から取得した個人情報の重要性を認識し、保護することを当社の事業活動の基本であると共に経営上の最重要な課題の一つと考えています。 皆様へ安心・安全・信頼のサービスを提供していくため、以下のような基本方針を定め全社員に周知徹底を図り、これを遵守しています。" },
        { type: "h2", text: "1. 基本方針" },
        { type: "p", text: "当社は、個人情報保護法及び関連するその他の法令・規範を遵守します。また、個人情報保護に関する社内規程（以下「当社規程」といいます。）を定め、これを実施し、維持すると共に、継続的な改善に努めます。 当社は、個人情報保護に関する管理体制を確立するとともに、当社規程を役員及び従業員に周知し、その遵守徹底に努めます。 当社は、個人情報をお客様に明示した利用目的の範囲内で取り扱います。また、当社は、お客様からご提供頂いた個人情報を、お客様の同意がある場合又は正当な理由がある場合を除き、第三者に開示若しくは提供しません。 当社は、個人情報を正確かつ最新の状態に保つとともに、個人情報への不正アクセス、個人情報の漏えい、滅失、き損等の予防に努め、情報セキュリティの向上、是正を継続的に実施します。 当社は、お客様からの個人情報に関するお問い合わせ、開示等のご請求に誠実かつ迅速に対応します。" },
        { type: "p", text: "【事業者情報】" },
        { type: "li", list: "ul", text: "会社名：メディカルインフォマティクス株式会社" },
        { type: "li", list: "ul", text: "住所：東京都千代田区丸の内二丁目1番1号 明治生命館4階" },
        { type: "li", list: "ul", text: "代表者：代表取締役 佐々木 美樹" },
        { type: "h2", text: "2. 個人情報の利用目的" },
        { type: "p", text: "当社は、お客様から個人情報をご提供頂く場合、予め個人情報の利用目的を明示し、その利用目的の範囲内で利用します。 予め明示した利用目的の範囲を超えて、お客様の個人情報を利用する必要が生じた場合は、お客様にその旨をご連絡し、お客様の同意を頂いた上で利用します。 当社が保有する個人情報の利用目的は下記の通りです。" },
        { type: "h3", text: "⑴ お取引先様に関する個人情報" },
        { type: "li", list: "ul", text: "医療機関向けコンサルティング、電子カルテシステムの開発・販売・保守、医療機関向けBPOサービス、及び医師紹介サービスの提供" },
        { type: "li", list: "ul", text: "お客様との商談、お打ち合わせ、及び契約の履行" },
        { type: "li", list: "ul", text: "当社が提供するサービスに関連するご案内、資料、メールマガジンの送付" },
        { type: "li", list: "ul", text: "各種会員制サービス、製品の導入支援及びカスタマーサポートの提供" },
        { type: "li", list: "ul", text: "お問い合わせ、ご相談への対応" },
        { type: "h3", text: "⑵ Care24Japanの利用者に関する個人情報" },
        { type: "li", list: "ul", text: "本サービスにおけるマッチング、本人確認、及びサービスの提供" },
        { type: "li", list: "ul", text: "ご利用料金の請求、決済、及びそれに伴う事務手続き" },
        { type: "li", list: "ul", text: "本サービスに関するカスタマーサポート、メンテナンスの提供、及びお問い合わせ・ご相談への対応" },
        { type: "li", list: "ul", text: "本サービスに関するご案内、広告及び資料の送付" },
        { type: "li", list: "ul", text: "規約変更等、本サービスに関する重要なお知らせの通知" },
        { type: "h3", text: "⑶ Care24Japanのケアサポーター（登録ワーカー）に関する個人情報" },
        { type: "li", list: "ul", text: "登録審査、スキル・資格の確認、及び本人確認" },
        { type: "li", list: "ul", text: "プラットフォーム上でのマッチング、及び利用者へのプロフィール等の情報開示" },
        { type: "li", list: "ul", text: "報酬の支払い、お振込み事務、及びそれに伴う事務手続き" },
        { type: "li", list: "ul", text: "業務連絡、問い合わせ対応、及びサポート提供" },
        { type: "li", list: "ul", text: "サービス開発、アンケート調査実施、モニター等の実施" },
        { type: "h3", text: "⑷ 取材対象者・その他の皆様に関する個人情報" },
        { type: "li", list: "ul", text: "記事コンテンツ作成の為の取材対象者の募集及び連絡" },
        { type: "li", list: "ul", text: "お問い合わせ・ご相談への対応" },
        { type: "h3", text: "⑸ 採用応募者に関する個人情報" },
        { type: "li", list: "ul", text: "採用応募者（インターンシップを含む）への採用情報等の提供・連絡" },
        { type: "li", list: "ul", text: "当社での採用選考、合否判定及び採用業務管理" },
        { type: "h2", text: "3. 個人情報の適正な取得" },
        { type: "p", text: "当社では、個人情報の取得は、適法かつ公正な手段で行います。なお、当社への個人情報の提供は任意ですが、必要な情報をご提供いただけない場合、各サービスの全部又は一部をご利用いただけない場合があります。" },
        { type: "h2", text: "4. 個人情報の提供" },
        { type: "p", text: "当社は、次の場合を除き、お客様の個人情報を第三者に開示または提供しません。" },
        { type: "li", list: "ol", text: "お客様の同意がある場合（マッチング成立に伴い、利用者と登録ワーカー間で相互に相手方の必要情報を開示する場合を含みます。）" },
        { type: "li", list: "ol", text: "法令に基づく場合" },
        { type: "li", list: "ol", text: "人の生命、身体又は財産の保護のために必要であって、お客様の同意を取ることが困難な場合" },
        { type: "li", list: "ol", text: "利用目的の達成に必要な範囲で、個人情報の取扱いを委託する場合" },
        { type: "li", list: "ol", text: "合併、会社分割、営業譲渡その他の事由によって事業の承継が行われる場合" },
        { type: "h2", text: "5. 個人情報の委託について" },
        { type: "p", text: "前条にかかわらず、当社は、利用目的の達成に必要な範囲内において個人情報の取扱いの全部又は一部を委託する場合があります。 なお、個人情報の取扱いを委託する場合は、適切な委託先を選定し、個人情報が安全に管理されるよう適切に監督いたします。" },
        { type: "h2", text: "6. 安全管理措置について" },
        { type: "p", text: "当社は、個人情報への不正アクセス、個人情報の漏えい、滅失、き損等の予防及び安全管理のため、以下の措置を継続的に実施します。" },
        { type: "li", list: "ul", text: "組織体制の整備： 個人情報の取扱いに関する責任者を設置し、報告連絡体制を整備しています。" },
        { type: "li", list: "ul", text: "従業員の教育： 役員及び従業員に対し、個人情報の取扱いに関する定期的な教育・研修を実施しています。" },
        { type: "li", list: "ul", text: "物理的・技術的対策： 個人情報を取り扱う区域のアクセス制限、機器の盗難防止措置、及び外部からの不正アクセスを防ぐセキュリティ対策を導入しています。" },
        { type: "h2", text: "7. 個人情報に関するお問い合わせ及び開示手続き" },
        { type: "p", text: "お客様の個人情報の開示・訂正・削除、利用停止等（第三者提供記録の開示を含みます）に関するお問い合わせやご請求は、お問い合わせフォームよりご連絡ください。ご本人であることを確認させていただいたうえで、誠実かつ迅速に対応します。 なお、保有個人データの利用目的の通知及び開示請求につきましては、1件あたり1,000円（税抜）の手数料を申し受ける場合があります。" },
        { type: "h2", text: "8. その他の事項" },
        { type: "h3", text: "⑴ アクセス情報及びクッキーについて" },
        { type: "p", text: "当サイトでは、より良いサービスをご提供させて頂くために、アクセスログ情報やクッキー（Cookie）を取得・使用する場合がございます。これらは単独では特定の個人を識別することができないため、個人情報とは考えておりません。なお、クッキー情報については、ブラウザの設定で拒否することが可能です。" },
        { type: "h3", text: "⑵ 外部送信情報について" },
        { type: "p", text: "当社は、ユーザーの行動分析やサービスの改善、広告効果測定等のため、クッキー等の識別子を利用して以下の外部ツールへ情報を送信しています。" },
        { type: "table", rows: [["ツール名", "当社の利用目的", "情報の内容", "送信先及び送信先の利用目的"], ["AWS", "ユーザーの利用状況の把握、本サービスの運営管理及び改善", "広告識別子、端末やアプリの情報、ネットワークの情報、アクセス履歴、電話番号", "Amazon Web Services, Inc."], ["Google Analytics", "ユーザーの利用状況の把握、本サービスの運営管理及び改善", "広告識別子、端末やアプリの情報、ネットワークの情報、アクセス履歴", "Google LLC."], ["Google", "ユーザーの利用状況の把握、本サービスの運営管理及び改善", "広告識別子、端末やアプリの情報、ネットワークの情報、アクセス履歴、電話番号", "Google Inc."], ["Meta", "ユーザーの利用状況の把握、本サービスの運営管理及び改善", "広告識別子、端末やアプリの情報、ネットワークの情報、アクセス履歴、電話番号", "Meta Platforms, Inc."], ["LINE", "ユーザーの利用状況の把握、本サービスの運営管理及び改善", "広告識別子、端末やアプリの情報、ネットワークの情報、アクセス履歴、電話番号", "LINEヤフー株式会社"], ["Yahoo", "ユーザーの利用状況の把握、本サービスの運営管理及び改善", "広告識別子、端末やアプリの情報、ネットワークの情報、アクセス履歴、電話番号", "LINEヤフー株式会社"], ["X", "ユーザーの利用状況の把握、本サービスの運営管理及び改善", "広告識別子、端末やアプリの情報、ネットワークの情報、アクセス履歴、電話番号", "X Corp"]] },
        { type: "h3", text: "⑶ 統計データ・アンケート調査結果の利用について" },
        { type: "li", list: "ul", text: "統計データについて： 当社は提供を受けたお客様の個人情報をもとに、お客様個人を特定できないよう加工した統計データを作成することがあります。お客様個人を特定できない統計データについては、当社は、何ら制限なく利用することができるものとします。" },
        { type: "li", list: "ul", text: "アンケート調査結果について： 会員・登録ワーカーを対象に実施するアンケート調査の回答に含まれる、アンケート回答者本人以外の医療従事者の氏名、勤務先施設名及び勤務先都道府県を、事前に第三者提供について同意を得ている個人情報に付加して、当社サービスを利用する国内外の医療関係事業者に参考情報として提供いたします。" },
        { type: "li", list: "ul", text: "提供方法について： ID、パスワードを入力することよりアクセスが可能なWebページ上での表示、パスワードを設定したファイルを電子メール等に添付して送信し、若しくはこれを記録した記録媒体を授受すること、又はアクセスを制限したサーバー上でファイルを授受することによります。当社の会員情報と、取得した情報により作成したデータベースについて、既存情報と整合を確認し、データベースの更新を行っております。また、第三者から個人データの提供を受ける場合には、当該第三者の取得の経緯を確認し、適切な方法により取得いたします。" },
        { type: "h3", text: "⑷ 個人関連情報の取得および利用について" },
        { type: "p", text: "当社は、当社の提携事業者（当社の広告代理店、広告媒体その他の提携先をいいます、）より、当社の広告のクリック日時、広告媒体に関する情報（ID、サイト名等）、その他の個人関連情報（個人情報保護法に定めるものをいい、特定の個人を識別することができる情報は含みません。）の提供を受け、当該個人関連情報を、当社の保有する個人情報と紐付けて個人データとして取得及び利用する場合があります。当該情報は、広告の成果確認・効果測定のために利用されます。" },
        { type: "h3", text: "⑸ 個人情報関連の共同利用について" },
        { type: "p", text: "当社は、取得した個人情報を、当社のビジネスパートナー、業務提携会社その他当社が必要と認める第三者との間で共同利用させていただくことがあります。 当該共同利用にあたっては、共同利用者の範囲等の必要事項を定め、当社のウェブサイトに掲載することにより、当該必要事項を会員等の皆様が容易に知りうる状態におくこととします。" },
        { type: "li", list: "ul", text: "①共同利用される個人データの項目： 当社が取得した会員に関する個人情報のうち、下記項目を共同利用することがあります。 氏名、メールアドレス、電話番号、職種、所属先、セミナー参加情報、アンケート調査回答等、これらとウェブサイトの閲覧履歴を紐づけた情報の分析結果等" },
        { type: "li", list: "ul", text: "②共同して利用する者の範囲： 株式会社ワンダーラボラトリー（http://www.w-lab.jp/privacy/）" },
        { type: "li", list: "ul", text: "③共同して利用する者の利用目的： 本項第3号に記載した利用目的に同じ" },
        { type: "li", list: "ul", text: "④管理について責任を有するもの： メディカルインフォマティクス株式会社（代表者及び住所は第1項に記載の通り）" },
        { type: "p", text: "2026年7月10日 改定" },
      ],
      en: [
        { type: "p", text: "Medical Informatics Co., Ltd. (hereinafter referred to as the \"Company\") recognizes the importance of personal information obtained from stakeholders and considers its protection to be fundamental to our business activities and one of our most important management issues. In order to provide safe, secure, and reliable services to everyone, we have established the following basic policy, ensure that it is fully understood by all employees, and strictly comply with it." },
        { type: "h2", text: "1. Basic Policy" },
        { type: "li", list: "ul", text: "The Company complies with the Personal Information Protection Law and other related laws, regulations, and norms. In addition, we have established internal regulations regarding personal information protection (hereinafter referred to as \"Company Regulations\"), which we implement, maintain, and continuously strive to improve." },
        { type: "li", list: "ul", text: "The Company will establish a management system for personal information protection, inform executives and employees of the Company Regulations, and strive for strict compliance." },
        { type: "li", list: "ul", text: "The Company handles personal information within the scope of the purpose of use explicitly stated to the customer. Moreover, the Company will not disclose or provide personal information provided by customers to third parties, except when there is customer consent or a legitimate reason." },
        { type: "li", list: "ul", text: "The Company maintains personal information in an accurate and up-to-date state, strives to prevent unauthorized access to personal information, and the leakage, loss, or damage of personal information, and continuously implements and corrects information security measures." },
        { type: "li", list: "ul", text: "The Company responds sincerely and promptly to inquiries and requests for disclosure, etc., regarding personal information from customers." },
        { type: "p", text: "[Business Operator Information]" },
        { type: "li", list: "ul", text: "Company Name: Medical Informatics Co., Ltd." },
        { type: "li", list: "ul", text: "Address: 4F Meiji Seimei Kan, 2-1-1 Marunouchi, Chiyoda-ku, Tokyo" },
        { type: "li", list: "ul", text: "Representative: Miki Sasaki, Representative Director" },
        { type: "h2", text: "2. Purpose of Use of Personal Information" },
        { type: "p", text: "When the Company asks customers to provide personal information, we will specify the purpose of use in advance and use it within the scope of that purpose. If it becomes necessary to use a customer's personal information beyond the scope of the purpose of use specified in advance, we will notify the customer to that effect and obtain their consent before using it. The purposes of use of personal information held by the Company are as follows:" },
        { type: "h3", text: "(1) Personal information regarding business partners" },
        { type: "li", list: "ul", text: "Provision of consulting for medical institutions, development, sales, and maintenance of electronic medical record systems, BPO services for medical institutions, and physician referral services" },
        { type: "li", list: "ul", text: "Business negotiations, meetings with customers, and fulfillment of contracts" },
        { type: "li", list: "ul", text: "Sending information, materials, and email newsletters related to services provided by the Company" },
        { type: "li", list: "ul", text: "Provision of various membership services, product implementation support, and customer support" },
        { type: "li", list: "ul", text: "Responding to inquiries and consultations" },
        { type: "h3", text: "(2) Personal information regarding users of Care24Japan" },
        { type: "li", list: "ul", text: "Matching, identity verification, and provision of services in this service" },
        { type: "li", list: "ul", text: "Billing and settlement of usage fees, and related administrative procedures" },
        { type: "li", list: "ul", text: "Providing customer support and maintenance for this service, and responding to inquiries and consultations" },
        { type: "li", list: "ul", text: "Sending information, advertisements, and materials regarding this service" },
        { type: "li", list: "ul", text: "Notification of important notices related to this service, such as changes to the terms of service" },
        { type: "h3", text: "(3) Personal information regarding care supporters (registered workers) of Care24Japan" },
        { type: "li", list: "ul", text: "Registration screening, confirmation of skills/qualifications, and identity verification" },
        { type: "li", list: "ul", text: "Matching on the platform and disclosure of information such as profiles to users" },
        { type: "li", list: "ul", text: "Payment of remuneration, bank transfer administration, and related administrative procedures" },
        { type: "li", list: "ul", text: "Business communication, responding to inquiries, and providing support" },
        { type: "li", list: "ul", text: "Service development, implementation of questionnaire surveys, monitoring, etc." },
        { type: "h3", text: "(4) Personal information regarding interviewees and others" },
        { type: "li", list: "ul", text: "Recruitment and communication with interviewees for the creation of article content" },
        { type: "li", list: "ul", text: "Responding to inquiries and consultations" },
        { type: "h3", text: "(5) Personal information regarding employment applicants" },
        { type: "li", list: "ul", text: "Providing employment information and communicating with employment applicants (including internships)" },
        { type: "li", list: "ul", text: "Recruitment selection, pass/fail determination, and recruitment business management at the Company" },
        { type: "h2", text: "3. Proper Acquisition of Personal Information" },
        { type: "p", text: "The Company acquires personal information by lawful and fair means. The provision of personal information to the Company is voluntary, but if you do not provide the necessary information, you may not be able to use all or part of our respective services." },
        { type: "h2", text: "4. Provision of Personal Information" },
        { type: "p", text: "The Company will not disclose or provide your personal information to third parties except in the following cases:" },
        { type: "li", list: "ul", text: "With the customer's consent (including cases where the necessary information of the other party is mutually disclosed between the user and the registered worker upon successful matching)." },
        { type: "li", list: "ul", text: "When based on laws and regulations." },
        { type: "li", list: "ul", text: "When it is necessary for the protection of human life, body, or property, and it is difficult to obtain the customer's consent." },
        { type: "li", list: "ul", text: "When entrusting the handling of personal information within the scope necessary to achieve the purpose of use." },
        { type: "li", list: "ul", text: "When business is succeeded due to a merger, company split, business transfer, or other reasons." },
        { type: "h2", text: "5. Outsourcing of Personal Information" },
        { type: "p", text: "Notwithstanding the preceding article, the Company may outsource all or part of the handling of personal information within the scope necessary to achieve the purpose of use. When entrusting the handling of personal information, we will select an appropriate contractor and supervise them appropriately to ensure that personal information is securely managed." },
        { type: "h2", text: "6. Security Control Measures" },
        { type: "p", text: "The Company continuously implements the following measures to prevent unauthorized access to personal information, leakage, loss, or damage of personal information, and for security management." },
        { type: "li", list: "ul", text: "Improvement of organizational system: We have appointed a person responsible for the handling of personal information and have established a reporting and communication system." },
        { type: "li", list: "ul", text: "Employee training: We conduct regular education and training for executives and employees on the handling of personal information." },
        { type: "li", list: "ul", text: "Physical/technical measures: We have introduced access restrictions to areas where personal information is handled, measures to prevent theft of equipment, and security measures to prevent unauthorized access from the outside." },
        { type: "h2", text: "7. Inquiries and Disclosure Procedures Regarding Personal Information" },
        { type: "p", text: "For inquiries and requests regarding the disclosure, correction, deletion, suspension of use, etc., of your personal information (including disclosure of third-party provision records), please contact us via the inquiry form. We will respond sincerely and promptly after verifying your identity. Note that a fee of 1,000 yen (excluding tax) per request may be charged for the notification of the purpose of use and disclosure requests of retained personal data." },
        { type: "h2", text: "8. Other Matters" },
        { type: "h3", text: "(1) Access Information and Cookies" },
        { type: "p", text: "On this site, we may acquire and use access log information and cookies in order to provide better services. Since these alone cannot identify a specific individual, we do not consider them to be personal information. You can reject cookie information via your browser settings." },
        { type: "h3", text: "(2) External Transmission of Information" },
        { type: "p", text: "To analyze user behavior, improve services, and measure advertising effectiveness, the Company transmits information to the following external tools using identifiers such as cookies." },
        { type: "li", list: "ul", text: "AWS | Grasping user usage status, operation management and improvement of this service | Advertising identifier, device/app info, network info, access history, phone number | Amazon Web Services, Inc." },
        { type: "li", list: "ul", text: "Google Analytics | Grasping user usage status, operation management and improvement of this service | Advertising identifier, device/app info, network info, access history | Google LLC." },
        { type: "li", list: "ul", text: "Google | Grasping user usage status, operation management and improvement of this service | Advertising identifier, device/app info, network info, access history, phone number | Google Inc." },
        { type: "li", list: "ul", text: "Meta | Grasping user usage status, operation management and improvement of this service | Advertising identifier, device/app info, network info, access history, phone number | Meta Platforms, Inc." },
        { type: "li", list: "ul", text: "LINE | Grasping user usage status, operation management and improvement of this service | Advertising identifier, device/app info, network info, access history, phone number | LY Corporation" },
        { type: "li", list: "ul", text: "Yahoo | Grasping user usage status, operation management and improvement of this service | Advertising identifier, device/app info, network info, access history, phone number | LY Corporation" },
        { type: "li", list: "ul", text: "X | Grasping user usage status, operation management and improvement of this service | Advertising identifier, device/app info, network info, access history, phone number | X Corp" },
        { type: "h3", text: "(3) Use of Statistical Data and Questionnaire Survey Results" },
        { type: "li", list: "ul", text: "Regarding statistical data: The Company may create statistical data processed so that individual customers cannot be identified, based on the personal information provided. The Company may use statistical data that cannot identify an individual without any restrictions." },
        { type: "li", list: "ul", text: "Regarding questionnaire survey results: The names, affiliated facility names, and affiliated prefectures of medical professionals other than the survey respondents themselves, included in the responses to questionnaire surveys conducted for members/registered workers, will be added to personal information for which consent for third-party provision has been obtained in advance, and provided as reference information to domestic and overseas medical business operators who use our services." },
        { type: "li", list: "ul", text: "Regarding the method of provision: This is done by displaying on a web page accessible by entering an ID and password, sending a password-protected file attached to an email, etc., exchanging a recording medium recording this, or exchanging files on a server with restricted access. Regarding our member information and databases created from acquired information, we verify consistency with existing information and update the database. Furthermore, when receiving personal data from a third party, we will confirm the circumstances of acquisition by the third party and acquire it by an appropriate method." },
        { type: "h3", text: "(4) Acquisition and Use of Personal Related Information" },
        { type: "p", text: "The Company may receive from our business partners (meaning our advertising agencies, advertising media, and other partners) the date and time of clicks on our advertisements, information regarding advertising media (ID, site name, etc.), and other personal-related information (as defined in the Personal Information Protection Law, excluding information that can identify a specific individual). The Company may acquire and use this personal-related information as personal data by linking it with personal information held by the Company. Such information will be used for confirming the results and measuring the effectiveness of advertisements." },
        { type: "h3", text: "(5) Joint Use of Personal Information" },
        { type: "p", text: "The Company may jointly use acquired personal information with our business partners, business tie-up companies, and other third parties deemed necessary by the Company. In such joint use, necessary matters such as the scope of joint users will be determined and posted on our website to ensure that members, etc., can easily become aware of such necessary matters." },
        { type: "li", list: "ol", text: "Items of personal data to be jointly used: Among the personal information regarding members acquired by the Company, the following items may be jointly used. Name, email address, phone number, occupation, affiliation, seminar participation information, questionnaire survey responses, etc., and analysis results of information linking these with website browsing history." },
        { type: "li", list: "ol", text: "Scope of joint users: Wonder Laboratory Co., Ltd. (http://www.w-lab.jp/privacy/)" },
        { type: "li", list: "ol", text: "Purpose of use by joint users: Same as the purpose of use stated in item 3 of this section." },
        { type: "li", list: "ol", text: "Party responsible for management: Medical Informatics Co., Ltd. (Representative and address are as stated in paragraph 1)" },
        { type: "p", text: "Revised on July 10, 2026" },
      ],
    },
  },
  tokushoho: {
    heading: { ja: "特定商取引法に基づく表記", en: "Notation based on the Act on Specified Commercial Transactions" },
    body: {
      ja: [
        { type: "h2", text: "提供事業者の名称" },
        { type: "p", text: "メディカルインフォマティクス株式会社" },
        { type: "h2", text: "住所" },
        { type: "p", text: "〒100-0005 東京都千代田区丸の内二丁目1番1号 明治生命館4階" },
        { type: "h2", text: "代表者" },
        { type: "p", text: "代表取締役 佐々木 美樹" },
        { type: "h2", text: "問い合わせ先" },
        { type: "p", text: "【問い合わせ専用メールアドレス】 からお問い合わせください。 ※上記宛にお問い合わせいただければ、連絡先電話番号についても遅滞なく開示いたします。 （※公開用電話番号を設定した場合は、「電話番号03-XXXX-XXXX」と直接記載）" },
        { type: "h2", text: "利用料金" },
        { type: "p", text: "ご利用料金については、[こちらの料金ページ](/pricing)をご確認ください。" },
        { type: "h2", text: "利用料金の支払い方法" },
        { type: "p", text: "クレジットカード決済、または口座振込のうち、お客様の選択した方法によりお支払いいただきます。" },
        { type: "h2", text: "利用料金以外に必要となる費用" },
        { type: "li", list: "ul", text: "サービス提供にかかる事務手数料、交通費、指名料、当日ケアサポーターによって立替え払いされた実費等が発生する場合があります。これらの費用については、上記料金表等に記載がありますのでご確認ください。" },
        { type: "li", list: "ul", text: "銀行振込（口座振込）のご利用時には、振込手数料がお客様のご負担となります。" },
        { type: "h2", text: "利用料金の支払い時期" },
        { type: "li", list: "ul", text: "クレジットカード決済の場合 予約成立時に決済が行われます。お引き落とし時期については、ご利用のクレジットカード会社にお問い合わせください。" },
        { type: "li", list: "ul", text: "口座振込の場合 ご利用お申し込み（予約リクエスト）後、当社指定の期日までにお振込みいただきます。（※入金確認をもって予約が成立します）" },
        { type: "h2", text: "サービスのご利用が可能となる時期" },
        { type: "p", text: "当社サービスに登録後、成立した予約に記載された日程にてご利用いただけます。" },
        { type: "h2", text: "返品、キャンセルに関する事項" },
        { type: "p", text: "本サービスの予約をキャンセルする場合には、当社の別途定める方法によりキャンセルの手続きを行うものとします。ただし、キャンセルを行う時期によってはキャンセル料が発生いたしますので、詳細は[キャンセルポリシー](/cancellation-policy)をご確認ください。" },
      ],
      en: [
        { type: "h2", text: "Name of Business Operator" },
        { type: "p", text: "Medical Informatics Co., Ltd." },
        { type: "h2", text: "Address" },
        { type: "p", text: "4F Meiji Seimei Kan, 2-1-1 Marunouchi, Chiyoda-ku, Tokyo 100-0005" },
        { type: "h2", text: "Representative" },
        { type: "p", text: "Miki Sasaki, Representative Director" },
        { type: "h2", text: "Contact Information" },
        { type: "p", text: "Please contact us via [Dedicated Inquiry Email Address]." },
        { type: "p", text: "*If you contact us at the address above, we will disclose our contact phone number without delay." },
        { type: "p", text: "(*If a public phone number is set, state it directly as \"Phone Number: 03-XXXX-XXXX\")" },
        { type: "h2", text: "Usage Fees" },
        { type: "p", text: "Regarding usage fees, please check [our pricing page](/pricing)." },
        { type: "h2", text: "Payment Method for Usage Fees" },
        { type: "p", text: "Payment must be made by the method chosen by the customer, either by credit card or bank transfer." },
        { type: "h2", text: "Costs Required Other Than Usage Fees" },
        { type: "p", text: "Administrative fees, transportation expenses, nomination fees, and actual expenses paid in advance by the care supporter on the day of service may be incurred for the provision of services. Please check the fee schedule mentioned above, as these costs are outlined there." },
        { type: "p", text: "When using a bank transfer, the transfer fee will be borne by the customer." },
        { type: "h2", text: "Timing of Payment for Usage Fees" },
        { type: "li", list: "ul", text: "For Credit Card Payment: Payment is processed when the reservation is confirmed. Please contact your credit card company regarding the exact billing timing." },
        { type: "li", list: "ul", text: "For Bank Transfer: After applying for use (reservation request), please transfer the funds by the date specified by the Company. (*The reservation is confirmed upon confirmation of payment.)" },
        { type: "h2", text: "Timing When Services Can Be Used" },
        { type: "p", text: "After registering for our service, you can use the service on the dates specified in the confirmed reservation." },
        { type: "h2", text: "Matters Regarding Returns and Cancellations" },
        { type: "p", text: "If you wish to cancel a reservation for this service, you must complete the cancellation procedures in accordance with the methods separately determined by the Company. However, please note that a cancellation fee may be incurred depending on the timing of the cancellation, so please check our [cancellation policy](/cancellation-policy) for details." },
      ],
    },
  },
  terms: {
    heading: { ja: "Care24Japan プラットフォーム利用規約（ケアサポーター向け）", en: "Care24Japan Platform Terms & Conditions (For Care Supporters)" },
    body: {
      ja: [
        { type: "p", text: "本規約は、メディカルインフォマティクス株式会社（以下「当社」といいます。）が運営する保険外在宅支援マッチングプラットフォーム「Care24Japan」（以下「本サービス」といいます。）の利用条件を定めるものです。本サービスに登録する看護師・介護士等のワーカー（以下「ケアサポーター」といいます。）は、本規約に同意の上、本サービスを利用するものとします。" },
        { type: "h2", text: "第1条（目的および当社の立ち位置）" },
        { type: "li", list: "ol", text: "本サービスは、訪問介護・在宅支援サービスおよび訪問看護サービス（以下総称して「ケアサービス」といいます。）の提供を希望する利用者（以下「契約者」といいます。）と、所定の資格を有するケアサポーターをマッチングするプラットフォームです。" },
        { type: "li", list: "ol", text: "当社は、契約者とケアサポーターとの間のマッチングおよび個別契約締結の場、ならびに本システムを通じた決済手段（集金代行窓口）を提供すると共に、契約者とケアサポーターに対するサポート・フォロー等を行う役割を担うものであり、契約者に対するケアサービスそのものの提供主体ではなく、またケアサポーターの雇用主でもありません。" },
        { type: "li", list: "ol", text: "ケアサービスに関する契約（以下「個別契約」といいます。）は、本システムを通じてマッチングが成立した時点で、契約者とケアサポーターとの間で直接の「準委任契約」として成立するものとします。" },
        { type: "h2", text: "第2条（ケアサービスの区分および業務の裁量）" },
        { type: "li", list: "ol", text: "ケアサポーターが本システムを通じて受託できるケアサービスは、以下の2つの区分に分かれ、ケアサポーターは自身が保有する資格に応じた区分を選択・受託するものとします。 (1) 訪問介護・在宅支援サービス：身体介助（入浴、排泄、食事介助等）、生活支援（調理、掃除、買い物等）、見守り、通院・外出の付き添い等 (2) 訪問看護サービス：健康状態の観察、療養上の世話、医師の指示に基づく医療処置（点滴、インスリン注射、褥瘡処置、カテーテル管理等）等" },
        { type: "li", list: "ol", text: "ケアサポーターは、独立した個人事業主（受託者）として、民法上の準委任契約に基づく「善良なる管理者の注意（善管注意義務）」をもって、自己裁量と責任において本件業務を遂行するものとします。当社とケアサポーターとの間に、指揮命令関係、雇用契約、労働契約またはこれらに類する関係は一切成立しません。" },
        { type: "h2", text: "第3条（個別契約の成立および業務の辞退）" },
        { type: "li", list: "ol", text: "ケアサポーターが、本システム上で契約者からの利用予約に対して受託の意思表示を行い、マッチングが完了した時点で、契約者とケアサポーターとの間の個別契約（準委任契約）が自動的に成立します。" },
        { type: "li", list: "ol", text: "個別契約における日時、場所、具体的な業務内容、および報酬額等の条件は、本システム上の確定画面および自動送信される電磁的記録の定めに従うものとします。" },
        { type: "li", list: "ol", text: "マッチング成立後、ケアサポーターの都合により当該業務を辞退（キャンセル）する場合、当社が別途定める報酬規程に基づき、所定のペナルティ（違約金の発生、またはマッチング率の低下措置等）が科される場合があり、ケアサポーターはこれを予め了承するものとします。" },
        { type: "h2", text: "第4条（訪問看護サービスにおける医療行為の特則）" },
        { type: "li", list: "ol", text: "ケアサポーターが第2条第1項第2号に定める「訪問看護サービス」に該当する業務を行う場合、看護師、准看護師等の有効な国家資格を保有していることを、事前に当社が定める方法で証明しなければなりません。" },
        { type: "li", list: "ol", text: "ケアサポーターは、契約者に対し医療行為を提供する場合は、契約者の主治医が発行した有効な「訪問看護指示書」の記載内容および指示の範囲内に限ってこれを行うものとします。" },
        { type: "li", list: "ol", text: "ケアサポーターは、有効な訪問看護指示書が提示されない場合、または指示の範囲を超える医療行為については、契約者から強い要求があった場合であっても、法律（保健師助産師看護師法）に基づき、一切これを行ってはなりません。" },
        { type: "h2", text: "第5条（業務報酬、システム手数料および支払い方法）" },
        { type: "li", list: "ol", text: "当社は、個別契約に基づきケアサポーターが業務を適切に完了し、かつ本システムを通じて所定の業務完了報告を行ったことを条件として、契約者から回収した利用料金から、当社所定の「プラットフォーム利用料（システム手数料）」を差し引いた金額（以下「業務報酬」といいます。）をケアサポーターに支払います。" },
        { type: "li", list: "ol", text: "業務報酬の計算（時間単価、各種加算、指名手当、交通費実費等）は、当社が別途本システム上または報酬規程で提示する料金表に従うものとします。" },
        { type: "li", list: "ol", text: "当社は、ケアサポーターから契約者に対する業務報酬（準委任の対価）の債権について、集金代行権限を授与されているものとします。" },
        { type: "li", list: "ol", text: "業務報酬の締め日、支払日、振込口座への送金フローについては、当社が別途定める報酬規程の定めに従うものとします。なお、振込手数料の負担は報酬規程に従います。" },
        { type: "h2", text: "第6条（直接契約および引き抜きの禁止）" },
        { type: "li", list: "ol", text: "ケアサポーターは、本サービスの利用期間中および本サービス退会後2年間、本システムを通じて知り合った契約者（利用者）に対し、本システムを介さずに直接ケアサービス（介護・看護業務等を含むがこれらに限られない）を提供し、または個別に雇用契約、業務委託契約、準委任契約その他の契約を締結してはなりません。" },
        { type: "li", list: "ol", text: "ケアサポーターが前項に違反した場合、ケアサポーターは当社に対し、違約金として金50万円、または当該直接契約によって当社が被った損害額（本来得られるはずであったプラットフォーム利用料相当額の3倍の金額を含む）のいずれか高い方の金額を直ちに支払うものとします。" },
        { type: "h2", text: "第7条（禁止事項）" },
        { type: "p", text: "ケアサポーターは、本サービスの利用および業務の遂行にあたり、以下の行為を行ってはなりません。" },
        { type: "li", list: "ol", text: "受託した業務の全部または一部を、当社の事前の書面による承諾なしに、他の第三者に再委託し、または代行させる行為（業務は必ずケアサポーター本人が直接遂行しなければなりません）。" },
        { type: "li", list: "ol", text: "契約者および被介護者・被看護者の人権と尊厳を傷つける行為、暴言、暴力、威嚇、ハラスメント行為、または名誉・信用を毀損する行為。" },
        { type: "li", list: "ol", text: "契約者の自宅等において、事前の明確な合意やシステム上の記録なしに、現金や貴金属などの高価な物品の管理・売買等を引き受ける行為。" },
        { type: "li", list: "ol", text: "本システムへの登録において、保有資格、実務経験、健康状態等について虚偽の情報を登録する行為。" },
        { type: "li", list: "ol", text: "その他、当社がプラットフォームの運営上不適切と判断する一切の行為。" },
        { type: "h2", text: "第8条（秘密保持および個人情報の保護）" },
        { type: "li", list: "ol", text: "ケアサポーターは、本サービスを通じて知り得た当社の営業秘密・システム情報、ならびに契約者および被介護者・被看護者の個人情報（病歴、家族構成、住所、身体状況、バイタルデータ等を含むがこれらに限られない）を、厳重に管理し、第三者に開示または漏洩してはなりません。" },
        { type: "li", list: "ol", text: "ケアサポーターは、前項の秘密情報および個人情報を、個別契約に基づく業務遂行以外の目的（SNS等への投稿、他用途への流用等を含む）に一切使用してはなりません。本条の規定は、本サービス退会後も永続的に有効に存続するものとする。" },
        { type: "h2", text: "第9条（免責および損害賠償）" },
        { type: "li", list: "ol", text: "ケアサービスは契約者とケアサポーターとの間の直接の準委任契約に基づき提供されるものであるため、業務遂行に伴い発生した契約者または被介護者・被看護者の怪我、病状の悪化、死亡、または器物破損、盗難等のトラブルについて、ケアサポーターが民法上の善管注意義務違反（過失）の有無に応じて直接責任を負うものとし、当社は原則として一切の責任を負わないものとします。" },
        { type: "li", list: "ol", text: "前項の場合において、当社が加入する本システム向けの賠償責任保険が適用できる場合は、当該保険金の支払額を上限として損害の補填（カスタマーサポートを通じた対応）を行うことができるものとします。ただし、これによりケアサポーターの法的責任が全面的に免除されるものではありません。" },
        { type: "li", list: "ol", text: "ケアサポーターが本規約に違反し、または業務遂行において当社に損害を与えた場合、ケアサポーターはその損害（合理的な弁護士費用を含む）を賠償する責任を負います。" },
        { type: "h2", text: "第10条（規約の変更および利用停止）" },
        { type: "li", list: "ol", text: "当社は、必要と判断した場合には、ケアサポーターに事前に通知（本システム上での掲示、または登録されたメールアドレスへの送信）することにより、本規約および料金表、ガイドライン等の関連規程をいつでも変更することができるものとします。変更後にケアサポーターが本サービスを利用した場合、変更後の規約に同意したものとみなします。" },
        { type: "li", list: "ol", text: "ケアサポーターが本規約に違反した場合、または登録ワーカーとして不適当と当社が判断した場合、当社は何らの通知・催告を要せず、直ちに本システムの利用停止、マッチングの取消、または登録抹消（強制退会）の措置を講じることができるものとします。" },
        { type: "h2", text: "第11条（準拠法および管轄裁判所）" },
        { type: "li", list: "ol", text: "本規約の解釈および適用にあたっては、日本法を準拠法とします。" },
        { type: "li", list: "ol", text: "本サービスまたは個別契約に関して、ケアサポーターと当社の間で紛争が生じた場合には、当社の本店所在地を管轄する地方裁判所を第一審の専属的合意管轄裁判所とします。" },
        // TODO: enactment date placeholder — do not fill in; must be provided by the client/legal team.
        { type: "p", text: "2026年［〇］月［〇］日 制定" },
      ],
      en: [
        { type: "p", text: "These Terms of Use stipulate the conditions for using the out-of-pocket home care support matching platform \"Care24Japan\" (hereinafter referred to as \"this Service\") operated by Medical Informatics Co., Ltd. (hereinafter referred to as the \"Company\"). Workers such as nurses and caregivers who register for this Service (hereinafter referred to as \"Care Supporters\") shall use this Service after agreeing to these Terms." },
        { type: "h2", text: "Article 1 (Purpose and the Company's Position)" },
        { type: "li", list: "ul", text: "This Service is a platform that matches users (hereinafter referred to as \"Contractors\") who wish to receive home visiting care/home support services and visiting nursing services (hereinafter collectively referred to as \"Care Services\") with Care Supporters who possess prescribed qualifications." },
        { type: "li", list: "ul", text: "The Company plays the role of providing a place for matching and concluding individual contracts between Contractors and Care Supporters, as well as providing a payment method (payment collection agency window) through this system, and providing support and follow-up for Contractors and Care Supporters. The Company is not the entity providing the Care Service itself to the Contractor, nor is it the employer of the Care Supporter." },
        { type: "li", list: "ul", text: "The contract regarding the Care Service (hereinafter referred to as the \"Individual Contract\") shall be established directly between the Contractor and the Care Supporter as a \"quasi-mandate contract\" at the time the matching is established through this system." },
        { type: "h2", text: "Article 2 (Classification of Care Services and Discretion in Business)" },
        { type: "li", list: "ul", text: "The Care Services that Care Supporters can accept through this system are divided into the following two classifications, and Care Supporters shall select and accept the classification corresponding to their qualifications. (1) Home visiting care/home support services: Physical assistance (bathing, excretion, meal assistance, etc.), daily life support (cooking, cleaning, shopping, etc.), watching over, accompanying to hospitals/outings, etc. (2) Visiting nursing services: Observation of health condition, care for recuperation, medical treatment based on a doctor's instructions (intravenous drip, insulin injection, bedsore treatment, catheter management, etc.), etc." },
        { type: "li", list: "ul", text: "Care Supporters shall perform this business at their own discretion and responsibility as independent individual business owners (contractors) with the \"duty of care of a good manager\" based on a quasi-mandate contract under the Civil Code. No chain of command, employment contract, labor contract, or similar relationship is established between the Company and the Care Supporter." },
        { type: "h2", text: "Article 3 (Establishment of Individual Contracts and Decline of Business)" },
        { type: "li", list: "ul", text: "When a Care Supporter expresses their intention to accept a usage reservation from a Contractor on this system and the matching is completed, an Individual Contract (quasi-mandate contract) between the Contractor and the Care Supporter is automatically established." },
        { type: "li", list: "ul", text: "Conditions such as the date and time, location, specific business content, and remuneration amount in the Individual Contract shall be in accordance with the provisions of the confirmation screen on this system and automatically transmitted electromagnetic records." },
        { type: "li", list: "ul", text: "If a Care Supporter declines (cancels) the relevant business for their own reasons after matching is established, a prescribed penalty (such as the occurrence of a cancellation fee or a measure to lower the matching rate) may be imposed based on the remuneration regulations separately determined by the Company, and the Care Supporter shall consent to this in advance." },
        { type: "h2", text: "Article 4 (Special Rules for Medical Practices in Visiting Nursing Services)" },
        { type: "li", list: "ul", text: "When a Care Supporter performs business that falls under \"Visiting nursing services\" stipulated in Article 2, Paragraph 1, Item 2, they must prove in advance that they hold a valid national qualification such as a registered nurse or a licensed practical nurse by the method determined by the Company." },
        { type: "li", list: "ul", text: "When a Care Supporter provides medical practices to a Contractor, they shall do so only within the scope of the instructions and descriptions of a valid \"Visiting Nursing Instruction Document\" issued by the Contractor's attending physician." },
        { type: "li", list: "ul", text: "Care Supporters must not perform any medical practices that exceed the scope of instructions or when a valid visiting nursing instruction document is not presented, even if there is a strong request from the Contractor, based on the law (Act on Public Health Nurses, Midwives, and Nurses)." },
        { type: "h2", text: "Article 5 (Business Remuneration, System Usage Fee, and Payment Method)" },
        { type: "li", list: "ul", text: "On the condition that the Care Supporter properly completes the business based on the Individual Contract and reports the completion of the prescribed business through this system, the Company will pay the Care Supporter the amount remaining after deducting the \"platform usage fee (system fee)\" prescribed by the Company from the usage fee collected from the Contractor (hereinafter referred to as \"Business Remuneration\")." },
        { type: "li", list: "ul", text: "The calculation of Business Remuneration (hourly unit price, various additions, nomination allowance, actual transportation expenses, etc.) shall be in accordance with the fee schedule separately presented by the Company on this system or in the remuneration regulations." },
        { type: "li", list: "ul", text: "The Company is granted the authority to collect the claim for Business Remuneration (consideration for quasi-mandate) from the Contractor on behalf of the Care Supporter." },
        { type: "li", list: "ul", text: "The closing date, payment date, and remittance flow to the transfer account for Business Remuneration shall be in accordance with the provisions of the remuneration regulations separately determined by the Company. Note that the burden of the transfer fee follows the remuneration regulations." },
        { type: "h2", text: "Article 6 (Prohibition of Direct Contracts and Poaching)" },
        { type: "li", list: "ul", text: "Care Supporters must not provide care services (including but not limited to nursing care and nursing business) directly without using this system, or individually conclude employment contracts, business entrustment contracts, quasi-mandate contracts, or other contracts, with Contractors (users) they met through this system, during the usage period of this Service and for two years after withdrawing from this Service." },
        { type: "li", list: "ul", text: "If a Care Supporter violates the preceding paragraph, the Care Supporter shall immediately pay the Company 500,000 yen as a penalty, or the amount of damage suffered by the Company due to the direct contract (including an amount equivalent to three times the platform usage fee that should have originally been obtained), whichever is higher." },
        { type: "h2", text: "Article 7 (Prohibited Matters)" },
        { type: "p", text: "Care Supporters must not engage in the following acts when using this Service and performing business:" },
        { type: "li", list: "ul", text: "The act of subcontracting or having a third party act on behalf of all or part of the entrusted business without the Company's prior written consent (the business must always be directly executed by the Care Supporter themselves)." },
        { type: "li", list: "ul", text: "Acts that damage the human rights and dignity of Contractors and care receivers/nursing receivers, abusive language, violence, intimidation, harassment acts, or acts that defame or damage trust." },
        { type: "li", list: "ul", text: "The act of undertaking the management, buying and selling, etc. of expensive items such as cash and precious metals at the Contractor's home, etc., without prior clear agreement and records on the system." },
        { type: "li", list: "ul", text: "The act of registering false information regarding qualifications held, practical experience, health condition, etc. when registering on this system." },
        { type: "li", list: "ul", text: "Other acts that the Company determines to be inappropriate for the operation of the platform." },
        { type: "h2", text: "Article 8 (Confidentiality and Protection of Personal Information)" },
        { type: "li", list: "ul", text: "Care Supporters must strictly manage the Company's trade secrets and system information learned through this Service, as well as the personal information of Contractors and care receivers/nursing receivers (including but not limited to medical history, family structure, address, physical condition, vital data, etc.), and must not disclose or leak them to third parties." },
        { type: "li", list: "ul", text: "Care Supporters must not use the confidential information and personal information of the preceding paragraph for any purpose other than the execution of business based on the Individual Contract (including posting on SNS, diverting to other uses, etc.). The provisions of this article shall survive effectively in perpetuity even after withdrawing from this Service." },
        { type: "h2", text: "Article 9 (Disclaimer and Compensation for Damages)" },
        { type: "li", list: "ul", text: "Since Care Services are provided based on a direct quasi-mandate contract between the Contractor and the Care Supporter, the Care Supporter shall bear direct responsibility for troubles such as injuries, deterioration of medical conditions, death, or property damage and theft of Contractors or care receivers/nursing receivers that occur in conjunction with the execution of business, depending on the presence or absence of a breach of the duty of care of a good manager (negligence) under the Civil Code, and the Company shall in principle bear no responsibility whatsoever." },
        { type: "li", list: "ul", text: "In the case of the preceding paragraph, if the liability insurance for this system enrolled in by the Company can be applied, it shall be possible to compensate for damages (handling through customer support) up to the payment amount of the relevant insurance money. However, this does not completely exempt the Care Supporter's legal responsibility." },
        { type: "li", list: "ul", text: "If a Care Supporter violates these Terms or causes damage to the Company in the execution of business, the Care Supporter shall be liable to compensate for the damage (including reasonable attorney's fees)." },
        { type: "h2", text: "Article 10 (Changes to Terms and Suspension of Use)" },
        { type: "li", list: "ul", text: "The Company may change these Terms and related regulations such as the fee schedule and guidelines at any time by notifying Care Supporters in advance (posting on this system or sending to the registered email address) when it determines it to be necessary. If a Care Supporter uses this Service after the change, they are deemed to have agreed to the changed Terms." },
        { type: "li", list: "ul", text: "If a Care Supporter violates these Terms or if the Company determines that they are inappropriate as a registered worker, the Company may take measures such as immediately suspending the use of this system, canceling matching, or erasing registration (forced withdrawal) without requiring any notification or warning." },
        { type: "h2", text: "Article 11 (Governing Law and Jurisdiction)" },
        { type: "li", list: "ul", text: "The interpretation and application of these Terms shall be governed by Japanese law." },
        { type: "li", list: "ul", text: "If a dispute arises between a Care Supporter and the Company regarding this Service or an Individual Contract, the district court having jurisdiction over the location of the Company's head office shall be the exclusive agreement jurisdictional court of the first instance." },
        // TODO: enactment date placeholder — do not fill in; must be provided by the client/legal team.
        { type: "p", text: "Established on [Month] [Day], 2026" },
      ],
    },
  },
  cancellationPolicy: {
    heading: { ja: "Care24Japan キャンセルポリシー", en: "Care24Japan Cancellation Policy" },
    body: {
      ja: [
        { type: "h2", text: "第1条（目的）" },
        { type: "p", text: "本キャンセルポリシーは、メディカルインフォマティクス株式会社（以下「当社」という）が運営する「Care24Japan」（以下「本サービス」という）において、サービス利用者（以下「利用者」という）が予約確定した訪問介護・訪問看護・リハビリ等のマッチングサービス（以下「予約業務」という）を変更またはキャンセルする場合の条件およびキャンセル料について定めるものである。" },
        { type: "h2", text: "第2条（キャンセル料の発生基準および割合）" },
        { type: "p", text: "利用者の都合により予約業務をキャンセルまたは変更する場合、予約日時を基準とした以下のタイミングに応じてキャンセル料が発生するものとする。なお、判定基準となる時刻はすべて「15:00」を区切りとする。" },
        { type: "table", rows: [["キャンセル・変更の申し出タイミング", "キャンセル料の割合"], ["予約日の3日前の15:00以降のキャンセル・変更", "予約料金の 50％"], ["予約日の前々日の15:00以降のキャンセル・変更", "予約料金の 75％"], ["予約日の前日の15:00以降のキャンセル・変更", "予約料金の 100％（全額負担）"], ["上記（予約日3日前の15:00）より前のキャンセル・変更", "キャンセル料なし（無料）"]] },
        { type: "h2", text: "第3条（予約内容の変更時の取り扱い）" },
        { type: "li", list: "ol", text: "予約時間の短縮： 確定済みの予約時間を短縮する場合は、短縮された時間分をキャンセルとみなし、第2条の基準に基づき短縮分の料金に対して所定のキャンセル料が発生する。" },
        { type: "li", list: "ol", text: "予約時間の延長： 確定済みの予約時間を延長する場合は、延長部分を新たなスポット利用申込として取り扱い、延長分の追加料金が発生する。" },
        { type: "li", list: "ol", text: "日程変更の特例： 利用者または要介護者の都合による日程変更であっても、原則として第2条のキャンセル料が適用される。ただし、当社のシステムおよびケアサポーター（以下「サポーター」という）側が特別に了承した調整である場合はこの限りではない。調整後の日程が時間外や当日予約等の加算事由に該当する場合は、変更後のレートに基づき追加料金が発生する。" },
        { type: "h2", text: "第4条（指名予約および手当の取り扱い）" },
        { type: "p", text: "利用者がサポーターを指名して予約（指名予約）していた案件をキャンセルした場合、指名手数料（1時間あたり330円）についてもキャンセル料の対象となる。第2条に基づき基本料金のキャンセル料が50％または75％となる場合であっても、指名手数料についてはその全額（100％）がキャンセル料に加算される。ただし、キャンセル料が「なし（無料）」の期間内のキャンセルであれば、指名手数料のキャンセル料も発生しない。" },
        { type: "h2", text: "第5条（実費および交通費の取り扱い）" },
        { type: "p", text: "予約業務が事前にキャンセルされた場合、一律990円の交通費およびその他実費等の費用は発生しない。ただし、サポーターが既に訪問を開始しているなど、直前のキャンセルにより損害が発生した場合は実費相当分を請求することがある。" },
        { type: "h2", text: "第6条（当社またはサポーター都合によるキャンセル）" },
        { type: "p", text: "当社またはサポーターの突発的な体調不良、その他の不可抗力および都合により業務提供が不可能となり、予約がキャンセルされた場合は、利用者に対してキャンセル料は一切発生しない。" },
        { type: "h2", text: "附則" },
        { type: "p", text: "本ポリシーは、2026年9月1日より制定・施行する。" },
      ],
      en: [
        { type: "h2", text: "Article 1 (Purpose)" },
        { type: "p", text: "The purpose of this Cancellation Policy is to establish the conditions and cancellation fees when a service user (hereinafter referred to as the \"User\") changes or cancels a confirmed matching service reservation for visiting care, visiting nursing, rehabilitation, etc. (hereinafter referred to as the \"Reserved Work\") on \"Care24Japan\" (hereinafter referred to as \"this Service\") operated by Medical Informatics Inc. (hereinafter referred to as the \"Company\")." },
        { type: "h2", text: "Article 2 (Cancellation Fee Accrual Standards and Ratios)" },
        { type: "p", text: "If the Reserved Work is canceled or changed due to the User's convenience, a cancellation fee shall accrue depending on the following timing based on the reservation date and time. Furthermore, the base time for all judgments shall be cut off at \"15:00\"." },
        { type: "table", rows: [["Timing of Cancellation/Change Request", "Ratio of Cancellation Fee"], ["Cancellation/change after 15:00 three days prior to the reservation date", "50% of the reservation fee"], ["Cancellation/change after 15:00 two days prior to the reservation date", "75% of the reservation fee"], ["Cancellation/change after 15:00 the day before the reservation date", "100% of the reservation fee (full burden)"], ["Cancellation/change prior to the above (before 15:00 three days prior to the reservation date)", "No cancellation fee (Free)"]] },
        { type: "h2", text: "Article 3 (Handling of Changes to Reservation Details)" },
        { type: "li", list: "ul", text: "Shortening of reservation time: If a confirmed reservation time is shortened, the shortened time will be deemed a cancellation, and a predetermined cancellation fee will accrue for the shortened portion's fee based on the standards in Article 2." },
        { type: "li", list: "ul", text: "Extension of reservation time: If a confirmed reservation time is extended, the extended portion will be treated as a new spot usage application, and an additional fee for the extended portion will accrue." },
        { type: "li", list: "ul", text: "Exceptions for schedule changes: Even if a schedule change is due to the convenience of the User or the care recipient, the cancellation fee in Article 2 shall apply in principle. However, this shall not apply if the adjustment is specially approved by our system and the care supporter (hereinafter referred to as the \"Supporter\"). If the adjusted schedule falls under addition reasons such as overtime or same-day reservation, additional fees will accrue based on the modified rate." },
        { type: "h2", text: "Article 4 (Handling of Nomination Reservations and Allowances)" },
        { type: "p", text: "If a User cancels a case that was reserved by nominating a Supporter (nomination reservation), the nomination fee (330 yen per hour) shall also be subject to the cancellation fee. Even if the cancellation fee for the basic fee is 50% or 75% based on Article 2, the full amount (100%) of the nomination fee shall be added to the cancellation fee. However, if the cancellation occurs within the \"no cancellation fee (free)\" period, the cancellation fee for the nomination fee will not accrue." },
        { type: "h2", text: "Article 5 (Handling of Actual Expenses and Transportation Expenses)" },
        { type: "p", text: "If the Reserved Work is canceled in advance, the flat transportation fee of 990 yen and other actual expenses will not accrue. However, if damages occur due to a last-minute cancellation, such as the Supporter having already begun the visit, an amount equivalent to the actual expenses may be billed." },
        { type: "h2", text: "Article 6 (Cancellations due to the Company or Supporter's Convenience)" },
        { type: "p", text: "If the provision of work becomes impossible due to sudden illness of the Company or the Supporter, or other force majeure and convenience, resulting in the reservation being canceled, no cancellation fee whatsoever shall accrue to the User." },
        { type: "h2", text: "Supplementary Provisions" },
        { type: "p", text: "This Policy shall be enacted and enforced from September 1, 2026." },
      ],
    },
  },
  compensation: {
    heading: { ja: "Care24Japan ケアサポーター報酬規程", en: "Care24Japan Care Supporter Remuneration Regulations" },
    body: {
      ja: [
        { type: "h2", text: "第1条（目的）" },
        { type: "p", text: "本規程は、メディカルインフォマティクス株式会社（以下「当社」という）が運営する保険外訪問看護・訪問介護マッチングプラットフォーム「Care24Japan」（以下「本サービス」という）において、サービス利用者（以下「利用者」という）と準委任契約（以下「個別契約」という）を締結し、独立した請負人として業務を提供するケアサポーター（以下「サポーター」という）に対する報酬の支払いに関する基本事項を定めることを目的とする。" },
        { type: "h2", text: "第2条（契約関係）" },
        { type: "p", text: "サポーターは、本規程のほか、当社が定めるプラットフォーム利用規約を遵守しなければならない。サポーターと利用者との間に成立する法律関係は準委任契約であり、サポーターは独立した事業者として自己の裁量と責任において業務を遂行するものとし、当社とサポーターとの間に雇用契約その他指揮命令関係は存在しない。" },
        { type: "h2", text: "第3条（報酬の基本構成）" },
        { type: "p", text: "サポーターに支払われる報酬は、個別契約に基づくサービス提供実績に応じて算出される基本報酬、各種手当（時間外手当、当日予約手当、指名手当）、および交通費の合計額から、第6条に定めるプラットフォーム手数料を差し引いた金額とする。報酬の計算は、利用者が承認した実際のサービス提供時間（業務完了報告に基づき確定した時間）を基準として行う。" },
        { type: "h2", text: "第4条（報酬体系・単価一覧）" },
        { type: "p", text: "提供する業務区分（介護、看護、リハビリ）および時間帯等に応じたケアサポーター向け報酬単価は以下の通りとする（金額はすべて税込表示）。" },
        { type: "table", rows: [["業務区分", "区分・時間帯等条件", "お客様 支払い単価", "サポーター 報酬単価", "プラットフォーム 手数料"], ["介護業務 （初任者研修・実務者研修・介護福祉士・無資格等の適用範囲内業務）", "基本時間帯（9:00～18:00）", "¥3,740 / 時間", "¥2,000 / 時間", "¥1,740 / 時間"], ["", "時間外・夜間時間帯（18:00～9:00）", "¥4,488 / 時間", "¥2,200 / 時間", "¥2,288 / 時間"], ["", "当日予約（緊急募集案件）", "¥4,862 / 時間", "¥2,600 / 時間", "¥2,262 / 時間"], ["看護業務 （看護師・准看護師等有資格者限定業務）", "基本時間帯（9:00～18:00）", "¥6,600 / 時間", "¥3,300 / 時間", "¥3,300 / 時間"], ["", "時間外・夜間時間帯（18:00～9:00）", "¥7,920 / 時間", "¥3,630 / 時間", "¥4,290 / 時間"], ["", "当日予約（緊急募集案件）", "¥8,580 / 時間", "¥4,290 / 時間", "¥4,290 / 時間"], ["リハビリ業務 （理学療法士・作業療法士・言語聴覚士限定業務）", "基本時間帯（9:00～18:00）", "¥8,800 / 時間", "¥6,160 / 時間", "¥2,640 / 時間"]] },
        { type: "h2", text: "第5条（共通手当および交通費）" },
        { type: "p", text: "すべての業務区分において、以下の手当および交通費を共通として支給する。" },
        { type: "li", list: "ul", text: "指名手当： 利用者から特定のサポーターとして指名を受けて業務を行った場合、1時間あたり ¥330 を支給する。" },
        { type: "li", list: "ul", text: "交通費： 1回の訪問案件につき、一律 ¥990 を支給する。" },
        { type: "h2", text: "第6条（プラットフォーム手数料および決済代行）" },
        { type: "p", text: "利用者がサポーターに対して支払う個別契約の対価は、当社がプラットフォームとして受領を代行する。当社は、受領した対価から第4条に記載したプラットフォーム手数料を差し引いた上で、その残額をサポーターに対して支払うものとする。" },
        { type: "h2", text: "第7条（業務完了報告と報酬の確定）" },
        { type: "p", text: "サポーターは業務終了後、速やかに本サービスのシステムを通じて「業務完了報告」を行わなければならない。利用者による完了承認またはサービス実施報告が完了した案件について、毎月20日を締切日として支払報酬金額を確定する。確定した支払報酬金額は、当月末日までに支払うものとする。なお、20日以降に完了承認またはサービス実施報告が完了した案件については、翌月20日締めの対象とする。" },
        { type: "h2", text: "第8条（報酬の支払方法）" },
        { type: "p", text: "確定した報酬は、当社指定決済システムを通じ、サポーターがあらかじめ登録した銀行口座へ振り込まれるものとする。その際の振込手数料は当社が負担する。" },
        { type: "h2", text: "第9条（ケアサポーター都合によるキャンセル時の取り扱い）" },
        { type: "li", list: "ol", text: "ケアサポーターは、個別契約成立後、自己の都合により当該業務をキャンセルする場合、速やかに本システムを通じて利用者および当社へ通知しなければならない。" },
        { type: "li", list: "ol", text: "ケアサポーターの都合によるキャンセルが頻発する場合、または直前のキャンセルを行った場合、当社は以下の措置を講じることができるものとする。" },
        { type: "li", list: "ul", text: "(1) 当該案件にかかる報酬の全額不支給" },
        { type: "li", list: "ul", text: "(2) 当社が定める算定基準に基づく違約金の請求または報酬からの差し引き" },
        { type: "li", list: "ul", text: "(3) 本サービスの利用制限、またはアカウントの停止措置" },
        { type: "h2", text: "第10条（禁止事項およびペナルティに伴う報酬の制限）" },
        { type: "p", text: "サポーターが本サービスの利用規約または個別契約に違反した場合（利用者との直接交渉・中抜き行為、無断欠勤、ハラスメント行為、守秘義務違反等）、当社は該当する案件の報酬支払いを差し止め、またはアカウントの停止措置等を行うことができる。" },
        { type: "h2", text: "附則" },
        { type: "p", text: "本規程は、2026年9月1日より制定・施行する。" },
      ],
      en: [
        { type: "h2", text: "Article 1 (Purpose)" },
        { type: "p", text: "The purpose of these Regulations is to establish the basic matters regarding the payment of remuneration to care supporters (hereinafter referred to as \"Supporters\") who conclude a quasi-mandate contract (hereinafter referred to as \"Individual Contract\") with service users (hereinafter referred to as \"Users\") and provide services as independent contractors on the non-insurance visiting nursing and home care matching platform \"Care24Japan\" (hereinafter referred to as \"the Service\") operated by Medical Informatics Inc. (hereinafter referred to as \"the Company\")." },
        { type: "h2", text: "Article 2 (Contractual Relationship)" },
        { type: "p", text: "Supporters must comply with the platform terms of use established by the Company in addition to these Regulations. The legal relationship established between a Supporter and a User is a quasi-mandate contract, and the Supporter shall execute the work at their own discretion and responsibility as an independent business operator, and no employment contract or other direct-and-order relationship exists between the Company and the Supporter." },
        { type: "h2", text: "Article 3 (Basic Structure of Remuneration)" },
        { type: "p", text: "The remuneration paid to the Supporter shall be the total amount of the basic remuneration calculated according to the actual service provision based on the Individual Contract, various allowances (overtime allowance, same-day reservation allowance, nomination allowance), and transportation expenses, minus the platform fee specified in Article 6. The calculation of remuneration shall be based on the actual service provision time approved by the User (the time confirmed based on the work completion report)." },
        { type: "h2", text: "Article 4 (Remuneration Structure / Unit Price List)" },
        { type: "p", text: "The remuneration unit prices for care supporters according to the service category provided (caregiving, nursing, rehabilitation) and time zone, etc., are as follows (all amounts include tax)." },
        { type: "table", rows: [["Service Category", "Category / Time Zone Conditions", "Customer Payment Unit Price", "Supporter Remuneration Unit Price", "Platform Fee"], ["Caregiving Work  (Within the scope of applied work for Beginner's Training, Practical Training, Certified Care Worker, Unqualified, etc.)", "Basic Time Zone  (9:00 - 18:00)", "¥3,740 / Hour", "¥2,000 / Hour", "¥1,740 / Hour"], ["Caregiving Work  (Within the scope of applied work for Beginner's Training, Practical Training, Certified Care Worker, Unqualified, etc.)", "Overtime / Night Time Zone  (18:00 - 9:00)", "¥4,488 / Hour", "¥2,200 / Hour", "¥2,288 / Hour"], ["Caregiving Work  (Within the scope of applied work for Beginner's Training, Practical Training, Certified Care Worker, Unqualified, etc.)", "Same-day Reservation  (Urgent Recruitment Cases)", "¥4,862 / Hour", "¥2,600 / Hour", "¥2,262 / Hour"], ["Nursing Work  (Work limited to qualified persons such as Nurses and Assistant Nurses)", "Basic Time Zone  (9:00 - 18:00)", "¥6,600 / Hour", "¥3,300 / Hour", "¥3,300 / Hour"], ["Nursing Work  (Work limited to qualified persons such as Nurses and Assistant Nurses)", "Overtime / Night Time Zone  (18:00 - 9:00)", "¥7,920 / Hour", "¥3,630 / Hour", "¥4,290 / Hour"], ["Nursing Work  (Work limited to qualified persons such as Nurses and Assistant Nurses)", "Same-day Reservation  (Urgent Recruitment Cases)", "¥8,580 / Hour", "¥4,290 / Hour", "¥4,290 / Hour"], ["Rehabilitation Work  (Work limited to Physical Therapists, Occupational Therapists, and Speech-Language-Hearing Therapists)", "Basic Time Zone  (9:00 - 18:00)", "¥8,800 / Hour", "¥6,160 / Hour", "¥2,640 / Hour"]] },
        { type: "h2", text: "Article 5 (Common Allowances and Transportation Expenses)" },
        { type: "p", text: "Across all service categories, the following allowances and transportation expenses shall be provided commonly:" },
        { type: "li", list: "ul", text: "Nomination Allowance: If the work is performed after being nominated as a specific Supporter by the User, ¥330 per hour will be paid." },
        { type: "li", list: "ul", text: "Transportation Expenses: A flat rate of ¥990 will be paid per visit case." },
        { type: "h2", text: "Article 6 (Platform Fee and Payment Agency)" },
        { type: "p", text: "The Company shall act as a platform to receive the consideration for the Individual Contract paid by the User to the Supporter on their behalf. The Company shall deduct the platform fee described in Article 4 from the received consideration, and pay the remaining balance to the Supporter." },
        { type: "h2", text: "Article 7 (Work Completion Report and Confirmation of Remuneration)" },
        { type: "p", text: "After the completion of the work, the Supporter must promptly submit a \"Work Completion Report\" through the system of this Service. The payment remuneration amount will be confirmed with the 20th of each month as the cutoff date for cases where the completion approval or service execution report by the User has been completed. The confirmed payment remuneration amount shall be paid by the last day of the current month. Furthermore, cases where the completion approval or service execution report is completed after the 20th shall be subject to the cutoff on the 20th of the following month." },
        { type: "h2", text: "Article 8 (Payment Method of Remuneration)" },
        { type: "p", text: "The confirmed remuneration shall be transferred to the bank account registered in advance by the Supporter through the payment system designated by the Company. The transfer fee at that time shall be borne by the Company." },
        { type: "h2", text: "Article 9 (Handling of Cancellations due to Care Supporter's Convenience)" },
        { type: "p", text: "If a Care Supporter cancels the work for their own reasons after the Individual Contract has been established, they must promptly notify the User and the Company through this system. If cancellations due to the Care Supporter's convenience occur frequently, or if a last-minute cancellation is made, the Company may take the following measures:" },
        { type: "li", list: "ol", text: "Total non-payment of remuneration for the relevant case" },
        { type: "li", list: "ol", text: "Claiming of a penalty based on the calculation standards established by the Company or deduction from the remuneration" },
        { type: "li", list: "ol", text: "Restriction on the use of this Service, or account suspension measures" },
        { type: "h2", text: "Article 10 (Prohibitions and Restriction of Remuneration due to Penalties)" },
        { type: "p", text: "If a Supporter violates the terms of use of this Service or an Individual Contract (direct negotiation with a User/bypassing the platform, unauthorized absence, harassment behavior, breach of confidentiality obligation, etc.), the Company may suspend the payment of remuneration for the relevant case, or take measures such as account suspension." },
        { type: "h2", text: "Supplementary Provisions" },
        { type: "p", text: "These Regulations shall be enacted and enforced from September 1, 2026." },
      ],
    },
  },
  quasiMandate: {
    heading: { ja: "ケアサービス準委任契約書", en: "Care Service Quasi-Mandate Contract" },
    body: {
      ja: [
        { type: "p", text: "本通知（書面）は、メディカルインフォマティクス株式会社（以下「当社」といいます。）が運営する「Care24Japan」プラットフォーム利用規約に基づき、以下の契約者とケアサポーターとの間で直接成立した個別準委任契約の内容を証明するものです。" },
        { type: "h2", text: "1. 契約当事者" },
        { type: "li", list: "ul", text: "委託者（契約者）： ［利用者の氏名］（住所：［利用者の登録住所］）" },
        { type: "li", list: "ul", text: "受託者（ケアサポーター）： ［ケアサポーターの氏名］（資格：［看護師 / 介護福祉士 等］）" },
        { type: "h2", text: "2. 契約の性質および準拠規約" },
        { type: "p", text: "本契約は、民法第656条に基づく「準委任契約」であり、両当事者は、それぞれが当社に対して同意した「Care24Japan プラットフォーム利用規約（契約者向けおよびケアギバー向け）」のすべての条項（直接契約の禁止、免責事項、秘密保持等を含みますが、これらに限られません）が本契約に適用され、本契約の一部を構成することに合意します。" },
        { type: "h2", text: "3. 委託業務（予約）内容" },
        { type: "p", text: "本契約に基づき、受託者が委託者に対して提供する業務の詳細は以下の通りです。" },
        { type: "li", list: "ul", text: "マッチング成立日時： 2026年［〇］月［〇］日 ［〇］時［〇］分" },
        { type: "li", list: "ul", text: "業務実施日時： 2026年［〇］月［〇］日 ［〇］時［〇］分 ～ ［〇］時［〇］分（計［〇］時間）" },
        { type: "li", list: "ul", text: "実施場所（訪問先）： ［訪問先住所・施設名等］" },
        { type: "li", list: "ul", text: "対象者（被介護・被看護者）： ［対象者の氏名］（委託者との関係：［本人 / 父 / 母 等］）" },
        { type: "li", list: "ul", text: "サービス区分： ［ ① 訪問介護・在宅支援サービス ／ ② 訪問看護サービス ］" },
        { type: "li", list: "ul", text: "具体的な業務内容： ［システムで選択・入力された内容を自動反映］ （例：バイタルチェック、点滴管理、褥瘡処置、口腔ケア、排泄介助、見守り 等）" },
        { type: "h2", text: "4. 訪問看護（医療行為）に関する特則（※サービス区分②の場合のみ適用）" },
        { type: "li", list: "ol", text: "本契約に基づく業務に医療行為が含まれる場合、委託者は主治医が発行した有効な「訪問看護指示書」を事前に提示していることを保証するものとし、受託者は当該指示書の範囲内に限って医療行為を行うものとします。" },
        { type: "li", list: "ol", text: "訪問看護指示書が提示されない場合、または指示の範囲を超える医療行為については、委託者から要求があった場合であっても、受託者はこれを拒否するものとし、その場合も委託料金の減額等は行われません。" },
        { type: "h2", text: "5. 委託料金（報酬）および支払い方法" },
        { type: "li", list: "ul", text: "基本料金： ［〇,〇〇〇］円（時間単価 ［〇,〇〇〇］円 × ［〇］時間）" },
        { type: "li", list: "ul", text: "各種加算・手当： ［〇,〇〇〇］円（夜間加算 / 当日加算 / 指名料 等）" },
        { type: "li", list: "ul", text: "交通費： ［〇,〇〇〇］円" },
        { type: "li", list: "ul", text: "合計委託料金（税込）： ［〇,〇〇〇］円" },
        { type: "li", list: "ul", text: "支払い方法： 委託者は、当社が指定する決済方法を通じて、上記の合計委託料金を支払うものとします。受託者は、当社に対して当該料金の集金代行権限を授与しており、委託者が当社への決済を完了した時点で、委託者の受託者に対する料金支払い債務は消滅します。" },
        { type: "h2", text: "6. キャンセルポリシー" },
        { type: "p", text: "マッチング成立後、委託者または受託者の都合により本契約を解約（予約キャンセル）する場合は、当社が別途料金表に定めるキャンセルポリシーが適用され、キャンセル確定のタイミングに応じた所定のキャンセル料またはペナルティが発生します。" },
        { type: "h2", text: "7. 紛争解決および責任の所在" },
        { type: "p", text: "本業務の遂行に伴い、受託者の故意または過失によって委託者に損害（怪我、器物破損等）が発生した場合、受託者は民法上の善管注意義務違反に基づく責任を直接負うものとし、プラットフォーム運営会社である当社は原則として責任を負いません。ただし、当社が加入する賠償責任保険が適用可能な場合は、その範囲内で補填が行われるものとします。" },
        { type: "p", text: "本契約は、当社システム上において、委託者の予約申込みに対して受託者が受諾の操作を行い、マッチング完了の電磁的記録が当社のサーバーに記録された時点をもって、有効に成立したものとみなします。" },
        { type: "p", text: "（本通知はシステムより自動配信されているため、署名・捺印は省略されます）" },
        { type: "p", text: "※「マッチング成立時にシステムから自動発行（メール送信または画面表示）される電子書面」としてシステムに組み込む想定" },
      ],
      en: [
        { type: "p", text: "This notice (document) certifies the details of the individual quasi-mandate contract established directly between the following Contractor and Care Supporter, based on the Terms of Use of the \"Care24Japan\" platform operated by Medical Informatics Inc. (hereinafter referred to as the \"Company\")." },
        { type: "h2", text: "1. Contracting Parties" },
        { type: "li", list: "ul", text: "Trustor (Contractor): [User's Name] (Address: [User's Registered Address])" },
        { type: "li", list: "ul", text: "Trustee (Care Supporter): [Care Supporter's Name] (Qualification: [Nurse / Certified Care Worker, etc.])" },
        { type: "h2", text: "2. Nature of Contract and Governing Terms" },
        { type: "p", text: "This contract is a \"Quasi-Mandate Contract\" pursuant to Article 656 of the Civil Code, and both parties agree that all provisions of the \"Care24Japan Platform Terms of Use (for Contractors and Caregivers)\" agreed upon by each party with the Company (including, but not limited to, the prohibition of direct contracting, disclaimers, and confidentiality) shall apply to this contract and form a part of it." },
        { type: "h2", text: "3. Details of Outsourced Work (Reservation)" },
        { type: "p", text: "The details of the work to be provided by the Trustee to the Trustor based on this contract are as follows:" },
        { type: "li", list: "ul", text: "Matching Establishment Date and Time: [Month] [Day], 2026, [Hour]:[Minute]" },
        { type: "li", list: "ul", text: "Work Execution Date and Time: [Month] [Day], 2026, [Hour]:[Minute] to [Hour]:[Minute] (Total: [X] hours)" },
        { type: "li", list: "ul", text: "Execution Location (Visit Destination): [Destination Address / Facility Name, etc.]" },
        { type: "li", list: "ul", text: "Target Person (Care/Nursing Recipient): [Target Person's Name] (Relationship to Trustor: [Self / Father / Mother, etc.])" },
        { type: "li", list: "ul", text: "Service Category: [ ① Home Care/In-Home Support Service / ② Visiting Nursing Service ]" },
        { type: "li", list: "ul", text: "Specific Work Details: [Automatically reflected from the content selected/entered in the system] (e.g., vital checks, IV management, bedsore treatment, oral care, excretion assistance, monitoring, etc.)" },
        { type: "h2", text: "4. Special Provisions regarding Visiting Nursing (Medical Practices) (Applicable only to Service Category ②)" },
        { type: "p", text: "If the work under this contract includes medical practices, the Trustor guarantees that a valid \"Visiting Nursing Instruction\" issued by the attending physician has been presented in advance, and the Trustee shall perform medical practices only within the scope of said instruction. If the Visiting Nursing Instruction is not presented, or for medical practices exceeding the scope of the instructions, the Trustee shall refuse to perform them even if requested by the Trustor, and in such cases, no reduction in the outsourcing fee shall be made." },
        { type: "h2", text: "5. Outsourcing Fee (Remuneration) and Payment Method" },
        { type: "li", list: "ul", text: "Basic Fee: [X,XXX] yen (Hourly rate [X,XXX] yen × [X] hours)" },
        { type: "li", list: "ul", text: "Various Additions/Allowances: [X,XXX] yen (Night addition / Same-day addition / Nomination fee, etc.)" },
        { type: "li", list: "ul", text: "Transportation Fee: [X,XXX] yen" },
        { type: "li", list: "ul", text: "Total Outsourcing Fee (Tax Included): [X,XXX] yen" },
        { type: "li", list: "ul", text: "Payment Method: The Trustor shall pay the total outsourcing fee above through the payment method designated by the Company. The Trustee has granted the Company the authority to collect said fee on their behalf, and the Trustor's obligation to pay the fee to the Trustee shall be extinguished at the time the Trustor completes the payment to the Company." },
        { type: "h2", text: "6. Cancellation Policy" },
        { type: "p", text: "After the matching is established, if this contract is terminated (reservation canceled) due to the convenience of the Trustor or the Trustee, the cancellation policy specified separately in the Company's fee schedule shall apply, and a predetermined cancellation fee or penalty will be incurred depending on the timing of the cancellation confirmation." },
        { type: "h2", text: "7. Dispute Resolution and Liability" },
        { type: "p", text: "If any damage (injury, property damage, etc.) is caused to the Trustor due to the Trustee's intent or negligence in the performance of this work, the Trustee shall bear direct liability based on a breach of the duty of care of a good manager under the Civil Code, and the Company, as the platform operating company, shall generally bear no liability. However, if the liability insurance enrolled in by the Company is applicable, compensation shall be provided within that scope." },
        { type: "p", text: "This contract is deemed to be validly established at the time the Trustee performs the acceptance operation in response to the Trustor's reservation application on the Company's system, and the electronic record of the matching completion is recorded on the Company's server." },
        { type: "p", text: "(Since this notice is automatically delivered from the system, signatures and seals are omitted)" },
        { type: "p", text: "*Intended to be integrated into the system as an \"electronic document automatically issued (emailed or displayed on screen) by the system upon matching establishment.\"" },
      ],
    },
  },
} satisfies Record<string, LegalDoc>;
