// Generated by @latellu/atlas-cli — DO NOT EDIT BY HAND.
// Workspace: care-24
// Source: https://api-c24jp.sipsedutech.id/api/v1/public/schema

export type Locale = "ja" | "en";

/** Site — 404 page labels (content type: "site-not-found-labels") */
export interface SiteNotFoundLabels {
  eyebrow?: string;
  title?: string; // localizable
  body?: string; // localizable
  home_label?: string; // localizable
  meta_description?: string; // localizable
}

/** Site — Error page labels (content type: "site-error-labels") */
export interface SiteErrorLabels {
  title?: string; // localizable
  body?: string; // localizable
  retry_label?: string; // localizable
}

/** Legal — Document (content type: "legal-doc") */
export interface LegalDoc {
  heading?: string; // localizable
  body?: string; // localizable
}

/** Company — Row (content type: "company-row") */
export interface CompanyRow {
  label?: string; // localizable
  value?: string; // localizable
  row_key?: string;
}

/** Service Flow — Step (content type: "service-flow-step") */
export interface ServiceFlowStep {
  title?: string; // localizable
  body?: string; // localizable
  number?: string;
}

/** Use Case — Item (content type: "use-case-item") */
export interface UseCaseItem {
  slug?: string;
  title?: string; // localizable
  body?: string; // localizable
  detail?: string; // localizable
  highlights?: string; // localizable
  image_alt?: string; // localizable
  image?: string;
}

/** Fees — Meta (content type: "fees-meta") */
export interface FeesMeta {
  column_customer?: string; // localizable
  column_supporter?: string; // localizable
  note?: string; // localizable
  column_service?: string; // localizable
  cta_href?: string;
}

/** Pricing — Meta (content type: "pricing-meta") */
export interface PricingMeta {
  highlights?: string; // localizable
  note?: string; // localizable
}

/** Rates — Row (content type: "rate-row") */
export interface RateRow {
  course_key?: string;
  row_key?: string;
  label?: string; // localizable
  detail?: string; // localizable
  customer_price?: number;
  supporter_pay?: number;
}

/** Rates — Course (content type: "rate-course") */
export interface RateCourse {
  course_key?: string;
  name?: string; // localizable
}

/** Home — Contact (content type: "home-contact") */
export interface HomeContact {
  lead_in?: string; // localizable
  heading?: string; // localizable
  hours?: string; // localizable
  isms?: string; // localizable
  mics_logo?: string;
  iso_logo?: string;
  mics_logo_alt?: string; // localizable
  iso_logo_alt?: string; // localizable
  contact_cta_href?: string;
  lead_in_ornament_start?: string; // localizable
  lead_in_ornament_end?: string; // localizable
}

/** Home — Apply banners (content type: "home-apply") */
export interface HomeApply {
  user_eyebrow?: string; // localizable
  user_label?: string; // localizable
  staff_eyebrow?: string; // localizable
  staff_label?: string; // localizable
  staff_href?: string;
  user_href?: string;
}

/** Home — Flow step (content type: "home-flow-step") */
export interface HomeFlowStep {
  number?: string;
  icon?: string;
  title?: string; // localizable
  body?: string; // localizable
}

/** Home — Flow header (content type: "home-flow") */
export interface HomeFlow {
  heading?: string; // localizable
  step_label?: string; // localizable
}

/** Home — Example case (content type: "home-example-case") */
export interface HomeExampleCase {
  label?: string; // localizable
  tone?: string;
  title?: string; // localizable
  request?: string; // localizable
  services?: string; // localizable
  hours?: string; // localizable
  schedule_times?: string;
  schedule_activities?: string; // localizable
}

/** Home — Examples header (content type: "home-examples") */
export interface HomeExamples {
  lead_in?: string; // localizable
  heading?: string; // localizable
  hours_label?: string; // localizable
  services_label?: string; // localizable
  schedule_label?: string; // localizable
}

/** Home — Nursing Course feature (content type: "home-nursing-feature") */
export interface HomeNursingFeature {
  icon?: string;
  label?: string; // localizable
}

/** Home — Nursing Course (content type: "home-nursing-course") */
export interface HomeNursingCourse {
  lead_in?: string; // localizable
  badge?: string; // localizable
  price_label?: string; // localizable
  price_hours?: string; // localizable
  price_amount?: string; // localizable
  price_unit?: string; // localizable
  price_tax_note?: string; // localizable
  price_tax_included?: string; // localizable
  note?: string; // localizable
  panel_heading?: string; // localizable
}

/** Home — Care Course service card (content type: "home-care-course-card") */
export interface HomeCareCourseCard {
  title?: string; // localizable
  image_alt?: string; // localizable
  items?: string; // localizable
  image?: string;
}

/** Home — Care Course fee cell (content type: "home-care-course-fee") */
export interface HomeCareCourseFee {
  label?: string; // localizable
  value?: string; // localizable
  note?: string; // localizable
}

/** Home — Care Course header (content type: "home-care-course") */
export interface HomeCareCourse {
  lead_in?: string; // localizable
  badge?: string; // localizable
  tagline?: string; // localizable
  tagline_sub?: string; // localizable
  price_label?: string; // localizable
  price_hours?: string; // localizable
  price_amount?: string; // localizable
  price_unit?: string; // localizable
  price_tax_note?: string; // localizable
  price_tax_included?: string; // localizable
}

/** Home — Problems (content type: "home-problems") */
export interface HomeProblems {
  heading?: string; // localizable
  items?: string; // localizable
}

/** Home — Values (trust strip) (content type: "home-values") */
export interface HomeValues {
  heading?: string; // localizable
  item_titles?: string; // localizable
  item_bodies?: string; // localizable
}

/** Home — Hero (content type: "home-hero") */
export interface HomeHero {
  badge?: string; // localizable
  resolve?: string; // localizable
  assist?: string; // localizable
  heading?: string; // localizable
  body?: string; // localizable
  cta_primary?: string; // localizable
  cta_secondary?: string; // localizable
  image_alt?: string; // localizable
  image?: string;
  cta_primary_href?: string;
  cta_secondary_href?: string;
}

/** Footer Legal Link (content type: "footer-legal-link") */
export interface FooterLegalLink {
  href?: string;
  label?: string; // localizable
  use_legal_heading?: string;
}

/** Site — Footer (content type: "site-footer") */
export interface SiteFooter {
  description?: string; // localizable
  legal?: string; // localizable
}

/** Nav Item (content type: "nav-item") */
export interface NavItem {
  href?: string;
  label?: string; // localizable
}

/** Site — UI chrome labels (content type: "site-ui-labels") */
export interface SiteUiLabels {
  menu_toggle_label?: string; // localizable
  tab_switch_label?: string; // localizable
  lang_toggle_label?: string; // localizable
  toc_label?: string; // localizable
  lang_short_ja?: string;
  lang_short_en?: string;
}

/** Site — Shared CTA labels (content type: "site-cta") */
export interface SiteCta {
  primary?: string; // localizable
  secondary?: string; // localizable
  contact?: string; // localizable
}

/** Site — Contact Phone (content type: "site-contact-phone") */
export interface SiteContactPhone {
  display?: string;
  tel?: string;
  note?: string; // localizable
}

/** Site — Brand (content type: "site-brand") */
export interface SiteBrand {
  name?: string;
  logo_alt?: string; // localizable
  tagline?: string; // localizable
  logo?: string;
}

/** Page Hero (content type: "page-hero") */
export interface PageHero {
  heading?: string; // localizable
  body?: string; // localizable
  cta_href?: string;
}

/** Maps each content-type slug to its entry interface. */
export interface AtlasContentTypes {
  "site-not-found-labels": SiteNotFoundLabels;
  "site-error-labels": SiteErrorLabels;
  "legal-doc": LegalDoc;
  "company-row": CompanyRow;
  "service-flow-step": ServiceFlowStep;
  "use-case-item": UseCaseItem;
  "fees-meta": FeesMeta;
  "pricing-meta": PricingMeta;
  "rate-row": RateRow;
  "rate-course": RateCourse;
  "home-contact": HomeContact;
  "home-apply": HomeApply;
  "home-flow-step": HomeFlowStep;
  "home-flow": HomeFlow;
  "home-example-case": HomeExampleCase;
  "home-examples": HomeExamples;
  "home-nursing-feature": HomeNursingFeature;
  "home-nursing-course": HomeNursingCourse;
  "home-care-course-card": HomeCareCourseCard;
  "home-care-course-fee": HomeCareCourseFee;
  "home-care-course": HomeCareCourse;
  "home-problems": HomeProblems;
  "home-values": HomeValues;
  "home-hero": HomeHero;
  "footer-legal-link": FooterLegalLink;
  "site-footer": SiteFooter;
  "nav-item": NavItem;
  "site-ui-labels": SiteUiLabels;
  "site-cta": SiteCta;
  "site-contact-phone": SiteContactPhone;
  "site-brand": SiteBrand;
  "page-hero": PageHero;
}
