import type { MetadataRoute } from "next";
import { brand } from "@/constants/copy";

/**
 * Closes the "manifest — none exist" line of the 2026-08-12 SEO/AEO audit
 * (Area A). Verified against node_modules/next/dist/docs/01-app/
 * 03-api-reference/03-file-conventions/01-metadata/manifest.md: a
 * `manifest.ts` under `app/` that default-exports a `MetadataRoute.Manifest`
 * is a special Route Handler that Next serves at `/manifest.webmanifest`
 * and auto-links from `<head>` — no `metadata.manifest` field is needed on
 * top of this file (unlike `icons.apple`, which does need an explicit
 * pointer; see app/[lang]/layout.tsx).
 *
 * This file sits outside `app/[lang]/`, so — same constraint as
 * `app/sitemap.ts` — it cannot read the `[lang]` route param and produces
 * one manifest for the whole site, not a per-locale one. "ja" is the
 * site's default, prefix-less language (features/lang/i18n.ts), so its
 * copy is used here rather than inventing a second, English manifest with
 * no route to serve it from.
 *
 * `name`/`short_name` both use the same `brand.name` ("Care 24 Japan")
 * already used everywhere else in the app (app/global-error.tsx,
 * app/global-not-found.tsx) — not a shortened/invented variant. Web App
 * Manifest's `short_name` is only used when space is constrained (e.g. a
 * home-screen icon label); reusing the one real brand string the codebase
 * has is safer than making up an abbreviation nobody approved.
 *
 * `description` reuses `constants/copy.ts`'s existing `brand.tagline.ja`
 * (the same string `app/[lang]/layout.tsx` falls back to for the
 * meta-description when no CMS value is set) rather than drafting new
 * copy, which is out of scope here.
 *
 * `background_color` is `--color-bg` (styles/globals.css) — the site's
 * actual page background — used for the splash screen Android shows while
 * the app loads. `theme_color` matches `app/[lang]/layout.tsx`'s
 * `export const viewport` (`--color-primary`, #2b7ec1) so the two
 * "browser chrome color" surfaces agree.
 *
 * Icons: generated by `scripts/atlas/make-icons.ts` (same pattern as
 * `scripts/atlas/make-og-card.ts`) — see that script for how
 * `icon-192.png`/`icon-512.png` were produced. `purpose: "any"` (the
 * default) rather than `"maskable"`: the source badge is not designed
 * with a maskable safe zone, so claiming `"maskable"` here would be a
 * false claim about content that was never built for it.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: brand.name,
    short_name: brand.name,
    description: brand.tagline.ja,
    lang: "ja",
    start_url: "/",
    display: "standalone",
    background_color: "#fafbff",
    theme_color: "#2b7ec1",
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
