import type { MetadataRoute } from "next";
import { getManifestContent } from "@/features/cms/site-manifest";

/**
 * Closes the "manifest — none exist" line of the 2026-08-12 SEO/AEO audit
 * (Area A). Verified against node_modules/next/dist/docs/01-app/
 * 03-api-reference/03-file-conventions/01-metadata/manifest.md: a
 * `manifest.ts` under `app/` that default-exports a `MetadataRoute.Manifest`
 * is a special Route Handler that Next serves at `/manifest.webmanifest`
 * and auto-links from `<head>` — no `metadata.manifest` field is needed on
 * top of this file (unlike `icons.apple`, which does need an explicit
 * pointer; see app/[lang]/layout.tsx).
 *
 * This file sits outside `app/[lang]/`, so — same constraint as
 * `app/sitemap.ts` — it cannot read the `[lang]` route param and produces
 * one manifest for the whole site, not a per-locale one. "ja" is the
 * site's default, prefix-less language (features/lang/i18n.ts), so its
 * copy is used here rather than inventing a second, English manifest with
 * no route to serve it from.
 *
 * CMS-DRIVEN, via the narrow `getManifestContent()` projection. It reads only
 * `site/site-brand.name` and `site/site-brand.tagline.ja`; the rendered
 * `site/footer` contract is intentionally not a dependency of this route.
 * If Atlas is unreachable or either required field is absent, the typed CMS
 * failure remains visible instead of returning stale bundled copy.
 *
 * Making the export `async` is what that costs. `manifest.js` is a Route
 * Handler that Next caches by default "unless it uses a Request-time API"
 * (node_modules/next/dist/docs/01-app/03-api-reference/03-file-conventions/
 * 01-metadata/manifest.md, "Generate a Manifest file"); `getManifestContent()`
 * reaches the strict `cache: "no-store"` CMS reader, so this
 * route renders per request like every other CMS-driven surface here.
 *
 * `name`/`short_name` both use the same `site/site-brand.name`
 * ("Care 24 Japan") already used everywhere else in the app — not a shortened/invented
 * variant. Web App Manifest's `short_name` is only used when space is
 * constrained (e.g. a home-screen icon label); reusing the one real brand
 * string the site has is safer than making up an abbreviation nobody
 * approved.
 *
 * `description` reuses the Japanese `site/site-brand.tagline` value rather
 * than drafting new copy, which is out of scope here.
 *
 * `background_color` is `--color-bg` (styles/globals.css) — the site's
 * actual page background — used for the splash screen Android shows while
 * the app loads. `theme_color` matches `app/[lang]/layout.tsx`'s
 * `export const viewport` (`--color-primary`, #2b7ec1) so the two
 * "browser chrome color" surfaces agree.
 *
 * Icons: generated by `scripts/atlas/make-icons.ts` (same pattern as
 * `scripts/atlas/make-og-card.ts`) — see that script for how
 * `icon-192.png`/`icon-512.png` were produced. `purpose: "any"` (the
 * default) rather than `"maskable"`: the source badge is not designed
 * with a maskable safe zone, so claiming `"maskable"` here would be a
 * false claim about content that was never built for it.
 */
/**
 * Declared dynamic EXPLICITLY, not left to inference. Next tries the static
 * pass first, `getManifestContent()`'s strict `cache: "no-store"` fetch throws
 * `DynamicServerError` mid-render, and Next then correctly re-marks the
 * route dynamic — the built output is identical either way. Declaring the
 * route dynamic skips that doomed static attempt.
 */
export const dynamic = "force-dynamic";

export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const { name, description } = await getManifestContent();

  return {
    name,
    short_name: name,
    description,
    lang: "ja",
    start_url: "/",
    display: "standalone",
    background_color: "#fafbff",
    theme_color: "#2b7ec1",
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
