import type { Metadata, Viewport } from "next";
import { notFound } from "next/navigation";
import "../../styles/globals.css";
import { notoSansJP } from "../fonts";
import AppShell from "@/components/AppShell";
import JsonLd, { organizationJsonLd } from "@/components/JsonLd";
import { SITE_URL } from "@/constants/site";
import { isLang, LANGS } from "@/features/lang/i18n";
import { getSite } from "@/features/cms/site";
import { getLegalHeading } from "@/features/cms/legal";
import { routeAlternates, titleTemplate } from "@/features/seo/pageMetadata";
import { ErrorLabelsProvider } from "./error-labels-provider";

// Dashboard edits must appear immediately, with no rebuild — see
// `features/cms/client.ts`'s `cache: "no-store"` on the delivery fetch.
// That option alone only stops the *fetch* from being cached; it does not
// stop Next from prerendering and caching the *route's rendered output* at
// build time (this route has no per-request API, so without this it looks
// static to the build). `dynamic = "force-dynamic"` here forces every
// route under `app/[lang]` to render fresh per request instead, per the
// route segment config docs (`node_modules/next/dist/docs/01-app/02-guides/
// caching-without-cache-components.md`) — this project doesn't use Cache
// Components (no `cacheComponents` flag in next.config.ts), so this is the
// applicable model.
export const dynamic = "force-dynamic";

/**
 * Static, not per-lang: theme-color and robots don't depend on `params`, so
 * per node_modules/next/dist/docs/01-app/03-api-reference/04-functions/
 * generate-viewport.md:67 ("If the viewport doesn't depend on request
 * information, it should be defined using the static `viewport` object
 * rather than `generateViewport`") this is a plain export, not a function —
 * and per generate-metadata.md:654 `themeColor` inside `metadata` is
 * deprecated since Next 14 in favor of this separate export.
 * Color is `--color-primary` from styles/globals.css (#2b7ec1) — the brand
 * color actually used site-wide for buttons/links/active nav state;
 * `--color-primary-deep` is declared in globals.css but not consumed by any
 * component today, so it is not the site's rendered "brand chrome" color.
 */
export const viewport: Viewport = {
  themeColor: "#2b7ec1",
};

export async function generateStaticParams() {
  return LANGS.map((lang) => ({ lang }));
}

export async function generateMetadata({
  params,
}: LayoutProps<"/[lang]">): Promise<Metadata> {
  const { lang } = await params;
  if (!isLang(lang)) notFound();

  const site = await getSite();

  return {
    metadataBase: new URL(SITE_URL),
    title: {
      // Em-dash here, NOT `titleTemplate`'s separator: home is the one
      // exception that bypasses `title.template` entirely (`default` wins
      // outright when there is no child-provided `title`, per
      // generate-metadata.md's title resolution rules), so this string is
      // hand-composed, not "%s"-templated — same reasoning
      // `features/seo/pageMetadata.ts#buildPageMetadataFields` documents for
      // why home's `og:title` also skips the brand suffix.
      default: `${site.brand.name} — ${site.brand.tagline[lang]}`,
      // `titleTemplate` is the ONE place the non-home separator is spelled
      // out — see its doc comment in features/seo/pageMetadata.ts for why
      // this can no longer drift from `og:title`/`twitter:title`.
      template: titleTemplate(site.brand.name),
    },
    description: site.brand.tagline[lang],
    alternates: routeAlternates("/", lang),
    // Explicit index/follow for both engine-wide (`robots`) and Google's own
    // crawler (`googleBot`) per generate-metadata.md:551-579 — previously
    // absent, so every page relied on the (also index/follow) HTTP default,
    // which is indistinguishable from "nobody decided this on purpose".
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
      },
    },
    openGraph: {
      type: "website",
      locale: lang === "ja" ? "ja_JP" : "en_US",
      siteName: site.brand.name,
    },
    // `public/apple-touch-icon.png` (180x180) is generated by
    // `scripts/atlas/make-icons.ts` from the badge mark already in
    // `public/images/logo.png` (same pattern as `make-og-card.ts`'s
    // `og-card.png`) — this field just points at it, the same way `icon`
    // already points at `/care24jpn.ico`.
    //
    // `manifest` is NOT set here: `app/manifest.ts` is a Next.js file
    // convention (like `app/sitemap.ts`), auto-detected and merged into
    // this metadata by Next itself (verified: `resolve-metadata.js:129,159`
    // reads `staticFilesMetadata.manifest` from the file convention output)
    // — setting it again here would be redundant, not additive.
    icons: {
      icon: "/care24jpn.ico",
      apple: "/apple-touch-icon.png",
    },
  };
}

export default async function RootLayout({
  children,
  params,
}: LayoutProps<"/[lang]">) {
  const { lang } = await params;
  if (!isLang(lang)) notFound();

  // Both reads are issued in the SAME tick, then awaited together.
  //
  // `AppShell` needs the tokushoho heading for the footer link label and asks
  // for it with its own `Promise.all` — but it is only rendered once this
  // function has returned, so by then `getSite()` has already resolved and
  // that `Promise.all` had nothing left to overlap (measured: the legal fetch
  // started 4ms AFTER the site fetch ended). Starting the heading read here
  // puts it in the first wave alongside `site`; because `getLegalHeading` is
  // React-`cache()`-ed, `AppShell` then picks up this very promise instead of
  // issuing a second request. Its value is deliberately dropped here — this
  // call exists to start the work, not to consume it.
  //
  // `getSite()` is deduped with the call in generateMetadata above (React
  // cache() again, per request), so neither of these is a second fetch either.
  //
  // Safe to put in a `Promise.all`, which rejects as soon as any input does:
  // `getLegalHeading` cannot reject. It is wrapped in its own try/catch and
  // returns the `constants/legal.ts` heading on every path, including an
  // unexpected throw (see the catch in features/cms/legal.ts, which explains
  // why the guard is there rather than relying on reasoning about internals).
  // So a footer link label cannot take this layout — i.e. every route, in
  // both locales — down.
  const [site] = await Promise.all([getSite(), getLegalHeading("legal-tokushoho")]);

  return (
    <html
      lang={lang}
      className={`${notoSansJP.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-bg text-body">
        <JsonLd data={organizationJsonLd(site)} />
        {/* `AppShell` (a Server Component) survived by definition whenever
            this renders — see error-labels-provider.tsx's doc comment on why
            `app/[lang]/error.tsx` can never activate from a failure inside
            THIS layout. Wraps AppShell entirely (not just `children`) purely
            for placement simplicity; Navbar/Footer ignore the context. */}
        <ErrorLabelsProvider value={site.errorPage}>
          <AppShell lang={lang}>{children}</AppShell>
        </ErrorLabelsProvider>
      </body>
    </html>
  );
}
